### ISSUE TITLE
可视模式（字符为主）支持

### ISSUE THREAD

**Issue by unc0** [dyng/ctrlsf.vim#10]
在 `s:Search()` 函数中：

```viml
if empty(args)
        if visualmode() != ''
            let args = '"' . escape(s:GetVisualSelection(), "(){}[]\'\"") . '"'
        else
            let args = expand('<cword>')
        endif
    endif
```

`s:GetVisualSelection()` 来自 http://stackoverflow.com/questions/1533565/how-to-get-visually-selected-text-in-vimscript/6271254#6271254

不知道是不是还有更多字符需要转义。

**Comment by dyng** [comment]
Added in 5dd714ee76d03c45199f0bbcffd970b09626cc54.
