### ISSUE TITLE
There is a Error for Me.

### ISSUE THREAD

**Issue by xushaobo** [dyng/ctrlsf.vim#100]
Error detected while processing function ctrlsf#Search..<SNR>149_ExecSearch..ctr
lsf#win#Draw..ctrlsf#view#Render..<SNR>163_Summary..ctrlsf#db#FileResultSet..ctr
lsf#db#FileResultSetBy:
line   13:
E684: list index out of range: -1
E116: Invalid arguments for function add
Error detected while processing function ctrlsf#Search..<SNR>149_ExecSearch..ctr
lsf#win#Draw..ctrlsf#view#Render:
line    7:
E712: Argument of extend() must be a List or Dictionary

**Comment by dyng** [comment]
If you have resolved your own problem, please leave a comment here to let me know if anything I can help, and also may help someone who shares same problem with you.

Thanks!
