### ISSUE TITLE
no support for ack 2.x

### ISSUE THREAD

**Issue by xvhfeng** [dyng/ctrlsf.vim#102]
when use ack in mac-os and ack verison is the lasted(2.x), ctrlsf.vim is not supported.
error msg:
Failed to call backend. Error messages: ack v1.39 Copyright 1993,94 Ogasawara Hiroyuki (COR.)
usage: ack [-{e|s|j|c[c]}] [-{a|A|o<file>}] [-zCntud] [-{E|S}] [<file>..]

**Comment by dyng** [comment]
> Failed to call backend. Error messages: ack v1.39 Copyright 1993,94 Ogasawara Hiroyuki (COR.)
usage: ack [-{e|s|j|c[c]}] [-{a|A|o}] [-zCntud] [-{E|S}] [..]

Your error message implies ack on your system is `v1.39` but not `v2.x`, please make sure you are using correct ack binary.

And if you need further help, **PLEASE FOLLOW INSTRUCTIONS IN ISSUE TEMPLATE**, which should be shown you in issue creation.
