### ISSUE TITLE
Feature request: move cursor to first result automatically

### ISSUE THREAD

**Issue by af** [dyng/ctrlsf.vim#104]
First of all, this is an amazing plugin, nice job! 

I was wondering what you think about moving the cursor to the first match automatically when the results window opens? I think this would be a nice convenience for the (common) case where you want to open the first result. It just saves one `<c-j>` keystroke but every little bit helps, and I can't think of any downside.

**Comment by dyng** [comment]
Moving cursor to the first match looks pretty fine! I'll implement this feature in this night or tomorrow.

Thanks for your nice suggestion.

**Comment by af** [comment]
Works great, thank you!
