### ISSUE TITLE
It's inserting spaces where there aren't any

### ISSUE THREAD

**Issue by svenstaro** [dyng/ctrlsf.vim#109]
For some reason, the ctrlsf window adds spaces where there aren't any in the source files. A screenshot to show this behavior with spaces highlighted in red: https://i.imgur.com/LBUdgTm.png

Left pane is ctrlsf which shows additional spaces. Right pane is normal vim buffer which shows that there are no spaces there. Why does this happen and how can I prevent it?

**Comment by dyng** [comment]
Those spaces are appended for indention. As those lines with content are indented in ctrlsf window, empty lines are indented too. You can configure how many spaces are used by setting `g:ctrlsf_indent`.

If you have trouble with combining CtrlSF with plugin that highlight trailing spaces, please add `ctrlsf` as excluded filetype. Take [vim-trailing-whitespace](https://github.com/bronson/vim-trailing-whitespace) as example:

```
let g:extra_whitespace_ignored_filetypes = ['ctrlsf']
```

Hope this can help you.

**Comment by svenstaro** [comment]
Awesome, that works, thanks a lot!
