### ISSUE TITLE
can not follow symbolic folder

### ISSUE THREAD

**Issue by freereaper** [dyng/ctrlsf.vim#111]
#### can not follow symbolic folder
when I have symbolic folder under my project folder, ctrlsf can not search the files under the symbolic folder even though I have set the "--follow" args. However, when I use ag in command line, it works like a charm.

#### vim configure
```
...
let g:ctrlsf_backend_args = {
   \  'ag' : '--follow',
   \}
```

#### some new features 

I hope the ctrlsf plugin can have the feature link ctrlp's ctrlp_working_path_mode settings, like bellow:
> let g:ctrlp_working_path_mode = 'ra'
  c - the directory of the current file.
  a - like "c", but only applies when the current working directory outside of
      CtrlP isn't a direct ancestor of the directory of the current file.
  r - the nearest ancestor that contains one of these directories or files:
      .git .hg .svn .bzr _darcs
  w - begin finding a root from the current working directory outside of CtrlP
      instead of from the directory of the current file (default). Only applies
      when "r" is also present.

because sometimes I have symbolic folders in my project, I want the ctrlsf to set it‘s working directory like the ctrlp  with 'w'  selection.

**Comment by dyng** [comment]
### For your first issue:

I have tested a symlink folder but can not reproduce your issue.

Please enable debug mode (by `let g:ctrlsf_debug_mode = 1`), then find the line starting with `ExecCommand: ...`, verify if `--follow` is passed to backend properly.

### For your second issue:

It's an acceptable feature. I'll take a look at it later.

**Comment by freereaper** [comment]
yep, I figured it out that g:ctrlsf_backend_args  should be g:ctrlsf_extar_backend_args, after i fix it, everything seems to be ok. But as I say, when I find the symbol and jump to the file in the symbolic folder, the ctrlsf's root dir changed, that's not what I want. Thanks for your magic plugin.

**Comment by dyng** [comment]
I have implemented a new option project+cwd for g:ctrlsf_default_root, which may solve your trouble. Please checkout feature/new-option-for-default-root branch and have a try.

I think it's not easy to cover all situations and hesitate to implement all options of CtrlP's `ctrlp_working_path_mode`. Let me know if you have any better idea. Thanks.

**Comment by freereaper** [comment]
Yep, I find that only works if the symbolic folder is not a VcsRoot, since you start searching the vcsRoot as the path from the current file, when returned Null, then begin finding the vcsRoot from the current work directory.

**Comment by dyng** [comment]
I'm not sure if I have truely understood your situation, if possible, please show me an example about your file structures, your problem and your expected results. Thanks.

**Comment by freereaper** [comment]
> A
> |--B .... C

 -------
A is a git repo , and B in A is a symbolic folder to the C dir which is not child dir of A. if  C is a git  repo too, using ctrlsf to search some symbols in the A dir(cwd), when jumping to the file in the C dir, the path of ctrlsf will be changed to C, obviously this result is not what I want.

**Comment by dyng** [comment]
I think in your case, maybe `let g:ctrlsf_default_root = 'cwd'` should meet your need. 

Anyway, I have implemented two sub-options for `g:ctrlsf_default_root` then grant more control over how CtrlSF find project root. In your case, `let g:ctrlsf_default_root = 'project+wf'` may solve your problem.

Please checkout `feature/new-option-for-default-root` branch and have a try.

**Comment by freereaper** [comment]
"project+wf" can meet my need, thanks for your work.
