### ISSUE TITLE
是否支持相对路径显示？

### ISSUE THREAD

**Issue by breezetemple** [dyng/ctrlsf.vim#114]
工程目录比较深，左右分屏显示时文件名不能完全显示，是否有配置用来相对getcwd()路径显示。
简单修改paragraph.vim可以正常显示，但是浏览文件不正常，谢谢！

**Comment by dyng** [comment]
目前暂不支持，但个人感觉不难实现。

因为相对路径仅仅在显示的时候需要，而内部数据结构中最好继续使用绝对路径。所以通过修改`view.vim`中的`s:Filemae`函数应该可以实现。

https://github.com/dyng/ctrlsf.vim/blob/master/autoload/ctrlsf/view.vim#L14-L17

**Comment by breezetemple** [comment]
已按照建议修改完毕，可以满足需求，谢谢！

**Comment by dyng** [comment]
@breezetemple 现已支持相对路径显示，请升级至最新版，如有问题请反馈 :)
