### ISSUE TITLE
"Vinegar"-style: reuse current window for CtrlSF

### ISSUE THREAD

**Issue by sergei-dyshel** [dyng/ctrlsf.vim#115]
Enhancement proposal:
Following "true" (:smile:) style of using [split windows instead of project drawer](http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/) it would be nice to open CtrlSF in the current split window and let it open search results in the other split.

Otherwise, when having 2 splits on 16:10 monitor and opening CtrlSF window as 3 split I end with something like this:

```
+------+--+--+
|CtrlSF| 1| 2|
+------+--+--+
```

where original splits (1 and 2) are two small and needs to be automatically resizing.
It worth mentioning that i use BIG fonts so opening thinner CtrlSF or splitting above/below is not convenient.

**Comment by skattyadz** [comment]
I've also thought about this. My file explorer and fuzzy find plugins both work this way and I find it prevents the case where window sizes don't get restored properly. That said, windows not restoring to their previous size could be a separate bug with ctrlsf or neovim

**Comment by skattyadz** [comment]
As a separate solution to both of our problems I guess you could open a tab and run a full-width ctrlsf in there?

**Comment by sergei-dyshel** [comment]
Currently I've ended with just opening CtrlSF window below (same way as for quickfix). But "vinegar"-style would be very nice feature :)

**Comment by dyng** [comment]
Sorry for this late reply.🐱 Things are messed up recently.

If I understand you correctly, currently CtrlSF will split into a new window and resize the rest windows
```
+------+--+--+
|CtrlSF| 1| 2|
+------+--+--+
```

but you prefer that CtrlSF should replace window 1 and like this:
```
+------+--+
|CtrlSF| 2|
+------+--+
```

At first I choose this "oil"-style with no reason but just I like this way used by *nerdtree* and *tagbar*, an alternative "vinegar"-style is not impossible but some questions should be answered first.

1. How does 'quit' (i.e. `q`) work? Restore previous buffer or close it?
2. If base window is not large enough, should CtrlSF change its size? or leave it to user?
3. If CtrlSF can change size of window 1 to meet its need, should CtrlSF also restore its size when quitting?

Any more question is welcome.

**Comment by sergei-dyshel** [comment]
1. Restore previous buffer. Also, `Enter` should reuse the window in which CtrlSF is opened. `<C-o>` should  open file in another window.
2,3. What are CtrlSF's window size requirements? I think in any reasonable multi-window setup (such as 16:9 screen split in 2-4 windows of equal size) the window will be big enough to fit CtrlSF but if it's not, you can leave it up to user.

**Comment by dyng** [comment]
There is another question is where to open preview window? I think a dedicated preview window is unavoidable.

The true reason why CtrlSF window will occupy half of Vim's window space to open by default, is that I want to leave the rest space to preview window. Here is my ideal layout when both CtrlSF window and preview window are opened. Notice that win1 and win2 are 1-column windows.

```
+------+-------+-+-+
|CtrlSF|Preview|1|2|
+------+-------+-+-+
```

When I'm using CtrlSF, most of the time I don't see original window but just focus in CtrlSF and preview window, so I think it's OK to resize them into small windows.

I'm afraid that I have not truly understood what is your problem. Which one of below is your problem? Or something else?

1. Original window is resized too small and hard to see.
2. Original window can't be restored to its original size after CtrlSF's quitting.

**Comment by sergei-dyshel** [comment]
In my case both are problems although I don't use  preview window that much.

Anyway, I think one aspect of "vinegar" idea is that the window layout is never modified by plugin and controlled only  by the user. Of course preview window doesn't go well with this approach and it don't have to since "vinegar" isn't the only way.  But it would be nice to have it for CtrlSF :smile:

**Comment by dyng** [comment]
A lot of changes need to be done if a new layout is introduced, it seems to be a big impact.

I'll consider it again in next major version, thanks for your suggestion.

**Comment by dyng** [comment]
Ctrlsf will not support "Vinegar"-style in the short future. Close this issue.

**Comment by daveyarwood** [comment]
In case it's helpful for others: I added `let g:ctrlsf_winsize = '100%'` to my vimrc to achieve something that's vinegarry enough for my tastes.

Pros:

* If I ignore the little line at the far right of the screen showing where it's split into 99.9% and 0.1%, I can convince myself that the CtrlSF buffer occupies the entire window.

* `q` works - it just closes the split.

Cons:

* Preview isn't usable. It opens in the remaining 0.1% of the window, so you can't see it.
  * I'm OK with this because I don't use the preview feature.

* It isn't true vinegar. If you have multiple splits open and then you open the CtrlSF buffer, it opens on top of everything else so all you can see is the CtrlSF buffer.
  * I'm OK with this because when I'm CtrlSF-ing for something, I don't want anything else to distract me; I just want to see the search results.
