### ISSUE TITLE
neovim terminal gets overwritten by preview window

### ISSUE THREAD

**Issue by chriad** [dyng/ctrlsf.vim#120]
![optimised](https://cloud.githubusercontent.com/assets/4353001/18361883/062b2fe2-7604-11e6-87b0-632a37aac08f.gif)

*The preview window overwrites the neovim console*

#### Things about your system and environment

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *Linux 2.6.32-642.3.1.el6.x86_64 #1 SMP Sun Jun 26 18:16:44 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux*        |
|   vim   | *NVIM v0.1.5-623-g4d4c925* |
| backend |             *ag 0.31.0*              |
| locale  |            *en_US.UTF-8*             |

- log:

- vimrc:

    ```vim
" ctrlsf
let g:ctrlsf_default_root = 'project'   
 ```

- file:

    The plugin that opens the neovim terminal is here: https://github.com/jalvesaq/Nvim-R .

**Comment by dyng** [comment]
I think it's more a neovim's issue than CtrlSF's issue.

When a preview window is brought up, other normal windows (including terminal simulator) will be resized to 1-column width window, then after preview window is closed, CtrlSF will try to restore those normal windows. But it seems that after a resize-and-restore operation, neovim's terminal simulator doesn't work well.
