### ISSUE TITLE
Feature request: Use 'P' to open preview window and switch focus to it

### ISSUE THREAD

**Issue by khingblue** [dyng/ctrlsf.vim#121]
In CtrlSF window, the key 'p' is my favorite. However, when I'd like to close the preview window, I have to switch to the preview window first before able to close it.

If can provide another key, like 'P', to open the preview window and switch focus to it, which has the same result as `p<Ctrl-w><Ctrl-w>`, that will be great.

**Comment by dyng** [comment]
A nice feature. I'll consider to implement it in next version.

**Comment by dyng** [comment]
Have implemented it in the latest version, please have a try. :)

Comment here if any issue.

**Comment by khingblue** [comment]
Works perfect. Thanks!

**Comment by dyng** [comment]
As the feature branch has merged, close this issue.
