### ISSUE TITLE
Exception caught: Vim(let):E484: Can't open file D:\jason\.ctrlsf_cmd_error_file in win10x64

### ISSUE THREAD

**Issue by fcymk2** [dyng/ctrlsf.vim#124]
It's run ok by v1.7.3 git a0196201fe2a4b7a6ee7c2f4064858f59b492669
The last version run ok in ubuntu, error in win10x64.
D:\jason is my $HOME fold

my vimrc config:
>    let g:ctrlsf_ackprg = 'ag'
    let g:ctrlsf_case_sensitive = 'smart'
    let g:ctrlsf_ignore_dir = ['tags', 'GTAGS', 'GPATH', 'GRTAGS', 'obj', 'out', 'lib*']

error_file:
>"test.h" 
"test.h" [unix] 89L, 2090C
Error detected while processing function <SNR>3_BMShow:
line   12:
E329: No menu "&Buffers"
Error detected while processing function <SNR>3_BMShow:
line   14:
E328: Menu only exists in another mode
Error detected while processing d:\tools\vim\plugged\neocomplete.vim\autoload\neocomplete\context_filetype.vim:
line   31:
E117: Unknown function: context_filetype#version

>Tokens: ['struct']
ParsedResult: {'pattern': 'struct'}
Options: {'pattern': 'struct', '_vimregex': '\V\cstruct', '_vimhlregex': '\V\c\(\^\d\+:\.\*\)\@<=struct'}
Tokens: ['-C', '3']
ParsedResult: {'context': 3}
ExecCommand: ag --context=3  --smart-case --ignore-dir "tags" --ignore-dir "GTAGS" --ignore-dir "GPATH" --ignore-dir "GRTAGS" --ignore-dir "obj" --ignore-dir "out" --ignore-dir "lib*" --literal --noheading --nogroup --nocolor --nobreak "struct" "d:\tools\.testvim\t"
Exception caught: Vim(let):E484: Can't open file D:\jason\.ctrlsf_cmd_error_file
HighlightRegex: /\V\c\(\^\d\+:\.\*\)\@<=struct/

**Comment by dyng** [comment]
It seems `~/.ctrlsf_cmd_error_log` does not work well in Windows. I'll try to use `tempname()` instead.

**Comment by dyng** [comment]
I have created a hotfix branch `hotfix/error-file-not-found-on-win`.

Sorry about that I can't verify it myself in windows, can you do me a favor to check if it works well? Thanks.

**Comment by fcymk2** [comment]
@dyng  I test in win10x64, work ok~~ tks~_~

**Comment by dyng** [comment]
Merged. Thanks for your bug report.
