### ISSUE TITLE
Feature request: :CtrlSFQuickfix to respect g:ctrlsf_auto_close

### ISSUE THREAD

**Issue by mateuszwieloch** [dyng/ctrlsf.vim#127]
First of all, this is really amazing plugin. Thanks so much! There's only one thing that's been bugging me.

Current behavior (with g:ctrlsf_auto_close set to 1):

1. :CtrlSFQuickfix <some_pattern>
2. <cr> to accept choice
3. quickfix window doesn't close

Expected behavior:

1. Close the quickfix window in step 3.

**Comment by dyng** [comment]
Actually `CtrlSFQuickfix` just open a plain-old quickfix window and leave it to user, not applying any custom mapping like ack.vim.

I'll consider about if I need a customized quickfix window.

**Comment by dyng** [comment]
CtrlSF mainly focuses its own editable window and all features are fully supported there. `CtrlSFQuickfix` command is an user request and I added it just as a complement, I don't want to port every feature and make it too complicated. Currently I'd rather leave its customization to user.

You can do it by adding these lines in your `.vimrc`. `Enter` or `o` to open a file, `q` to quit.

```vim
augroup quickfix
    autocmd!
    autocmd FileType qf nnoremap <expr><silent> <CR> g:ctrlsf_auto_close ? "<CR>:cclose<CR>" : "<CR>"
    autocmd FileType qf nnoremap <expr><silent> o    g:ctrlsf_auto_close ? "<CR>:cclose<CR>" : "<CR>"
    autocmd FileType qf nnoremap       <silent> q    :cclose<CR>
augroup END
```

**Comment by mateuszwieloch** [comment]
I see your point about keeping CtrlSF focused on a single task.

Thank you for sharing the snippet of code. I think an actual code to handle auto_close functionality properly would be a little bit more complicated. For ex the code you provided always opens file in a window above quickfix - which is a default behavior of vim, but CtrlSF already has a feature to open a file in a split that previously had focus. I'll follow your advice and just add proper code to my own `.vimrc`.
