### ISSUE TITLE
Async call with Vim 8

### ISSUE THREAD

**Issue by griffinqiu** [dyng/ctrlsf.vim#129]
The Vim 8 have already released.

Is ctrlsf possible async search?

**Comment by dyng** [comment]
Yes, I have considered about several features related to vim 8.0. If I have enough time, hopefully you can see them in the next major version.

Features:

- Async search.
- Unit tests.
- Overview window.
- Alternative layout.

**Comment by griffinqiu** [comment]
太棒了!
+10086

**Comment by skywind3000** [comment]
Vim 8.1 已经发布了，还没支持啊？我现在还在用 https://github.com/yegappan/grep 的原因就是人家支持 vim8，ctrlsf 稍微大的项目就卡的不行了，再 linux kernel 代码里搜索点东西，ctrlsf 直接卡了不会动，而 yegappan/grep 还能继续工作，边搜索边浏览文件。

**Comment by dyng** [comment]
@skywind3000 抱歉，因为近两年工作中很少用到vim，所以开发工作已经停滞。今天趁这个机会也研究了一下可行性，确实可以做成异步获取结果，解析并展示。不过因为当初设计时没有考虑过异步执行，所以改动量不小，估计需要两天才能完成。看我之后能不能抽出些时间来吧……

**Comment by skywind3000** [comment]
多谢，好插件，不跟进一下可惜了。

**Comment by skywind3000** [comment]
可以在 job 的 callback 中分析完了 setbufline，因为在运行过程中当前窗口可能切换或者被关闭。我封装过一个同时支持 vim8和 neovim 的 asynctask.vim:

https://github.com/skywind3000/vim/blob/master/autoload/asynctask.vim

没准能有点帮助。

**Comment by wsdjeg** [comment]
我大致考虑了下这个问题，可以实现，但是需要考虑以下问题:

1. 异步检索意味着搜索结束之前，用户可以执行其他操作，编辑，那么如果此时执行多光标编辑是否会漏结果，或者说像群里讨论那样完全禁止掉编辑。

2. vim 的job执行命令时是异步的，但callback函数并不是异步的。也就是说如果回调函数频繁调用会导致vim也很卡。另外就是，在追加buffer是，如果用户已经切到其他窗口怎么办？neovim支持跨buffer修改，vim不支持，需要通过py才能实现。
或者说是否需要跨buffer修改？还是用变量缓存，切到ctrlsf窗口时一次性修改？

**Comment by skywind3000** [comment]
Vim 可以跨 buffer 修改内容的：

```
setbufline({expr}, {lnum}, {text})			*setbufline()*
		Set line {lnum} to {text} in buffer {expr}.  To insert
		lines use |append()|.

		For the use of {expr}, see |bufname()| above.

		{lnum} is used like with |setline()|.
		This works like |setline()| for the specified buffer.
		On success 0 is returned, on failure 1 is returned.

		If {expr} is not a valid buffer or {lnum} is not valid, an
		error message is given.
```

**Comment by dyng** [comment]
多谢两位的意见，周末我抽一天时间来验证一下可行性吧。

**Comment by wsdjeg** [comment]
@skywind3000 这个方法太新了，不适合作为插件的依赖，他需要 8.0.1039. 而 Ubuntu 16.04 才是 7.4.1689 其实如果当前不再 ctrsf窗口时，对于窗口下面的内容是否再更新，并不一定关注，可以将需要更新内容存储再变量里，当首次切入时绘制窗口。

**Comment by dyng** [comment]
@wsdjeg 一边编辑一边更新搜索结果是我希望的效果，所以会使用`setbufline`，不过多谢你的支持版本信息。

**Comment by wsdjeg** [comment]
@dyng 那么如何解决依赖问题呢，比如 Ubuntu 16.04 这个版本使用的人不少，默认的 Vim 版本还没有这么高呢。

**Comment by dyng** [comment]
@wsdjeg 目前的想法是支持同步和异步两种模式，根据vim版本自动选择搜索模式。

**Comment by dyng** [comment]
今天做了个prototype验证了一下，相比于搜索，还是解析消耗的时间更多，所以结果返回时就比较卡。我研究一下是否有优化的可能，如果没有的话就只能考虑用python实现了。

**Comment by skywind3000** [comment]
可以流控，控制每秒钟解析的量即可，收到结果先缓存着timer里批量取出来解析，控制个量即可

**Comment by dyng** [comment]
@skywind3000 好主意！我找个时间再验证一下。

**Comment by dyng** [comment]
@skywind3000 @wsdjeg @griffinqiu 

实现了一个基础版本，在`feature/async-search`分支，想请大家帮忙测试一下，特别是在Windows和Linux上是否工作（我只测试了mac）

需要设置`let g:ctrlsf_search_mode = 'async'`打开异步搜索。

已知issue：

1. 报错和结果为空时行为不正确
2. 和`ag`的某些版本不兼容

**Comment by dyng** [comment]
@skywind3000 你用的是什么客户端？我使用`ag`时也有相同的症状，原因是`ag`返回的结果格式和预期的不同，导致解析失败。换做`rg`之后可用。

关于`ag`的格式问题我还在找原因。

**Comment by skywind3000** [comment]
客户端：GVim 8.1.39
我 ag, rg 都有，没特别设置过，不知道优先用的哪个。

**Comment by dyng** [comment]
现在默认优先使用的是`ag`，可以用`let g:ctrlsf_ackprg = 'rg'`切换成为`rg`再试试看。

**Comment by skywind3000** [comment]
设置了以后工作正常，但是发现一个小问题，

搜索比较耗时的情况下，我将光标焦点从左边的 ctrlsf 窗口移动到右边的旧窗口，发现左边只要一更新，就会把光标强制移动到左边窗口去了。

**Comment by skywind3000** [comment]
job/timer callback 中不建议做切换窗口（包括临时切换），这样用户的 combo 命令会被中断，比如打 `3dd` 才输入了头两个字母，如果被后台 callback 切换了窗口，哪怕后面切换回来该命令 combo 也中断了。

**Comment by dyng** [comment]
@skywind3000 目前有两个时间点会把用户光标切到ctrlsf窗口

1. 打开ctrlsf窗口时，包括搜索过程中关闭了窗口又重新打开
2. 搜索全部完成时

更新结果时应该不会切换光标才对，你是把结果窗口关闭了？

**Comment by skywind3000** [comment]
我没有关闭窗口，可能是碰到情况 2了，最后一个问题我觉得符合预期的，就该中断搜索。

**Comment by dyng** [comment]
@skywind3000 以上bug基本已经修完，请再试一下，看看有没有其他问题。

现在比较大的问题是只有`pt`和`rg`可以正常工作，`ag`的结果格式不正确，`ack`压根儿没有返回结果。

**Comment by dyng** [comment]
修好了，把stdin改成`null`就好了。好像是`ag`和`ack`在stdin是pipe时的行为会发生变化，`ack`会改为搜索stdin的内容（即使指定了搜索目录），`ag`则是输出格式会改变（不知道原因，怀疑是bug）。

**Comment by dyng** [comment]
现在应该只剩下一些用户体验的问题了，还请大家多提些意见😁

pull request准备先放两周时间给大家试用，我抽空再把文档补了。

**Comment by skywind3000** [comment]
恩，如果同时有 ag 和 rg 的话，优先使用 rg ?

**Comment by hy950831** [comment]
@dyng 刚刚有试验一下 async branch现在在neovim下无法运行\\
![image](https://user-images.githubusercontent.com/16500351/41213585-93ab42de-6d89-11e8-9c1f-66a73f8bc3ee.png)

**Comment by dyng** [comment]
@hy950831 `job_start()`是vim8.0新增的异步调用函数，看起来neovim还不支持。neovim目前还是自己的一套异步API。

**Comment by dyng** [comment]
@hy950831 发现API的差异还是有一些的，因为我自己也不用neovim，还是请neovim用户来帮忙实现兼容吧。另外我觉得现在vim8已经实现了异步API，使用neovim的必要性就不如以前了。

**Comment by hy950831** [comment]
@dyng 今天下午fork了并试图改写了一下, 发现vim和neovim的异步api还有buffer api都有区别. 等下周末期末考完之后我再仔细看一下

**Comment by dyng** [comment]
#212 已经 merge 进 master，感谢以上各位的帮助。

**Comment by skywind3000** [comment]
有问题，新版本再 Vim 8.1 下面如果什么都不设置，会报错：
![ctrlsf](https://user-images.githubusercontent.com/3035071/42018762-a3015944-7ae5-11e8-91c2-b75cac2e4d00.png)

**Comment by skywind3000** [comment]
不能重新打开？？
