### ISSUE TITLE
Can I search a word only match whole word?

### ISSUE THREAD

**Issue by fcying** [dyng/ctrlsf.vim#131]
like ag -w.
Or can i have any way to use ag parameter?

**Comment by dyng** [comment]
For your question, you can insert word boundary `\b` into your search pattern.

```vim
:CtrlSF -R "\bword\b"
```

There is also a configuration option `g:ctrlsf_extra_backend_args` you can use to pass arguments to backend, but usually it is used as a default setting for your backend, may be not very useful in your case.

**Comment by fcying** [comment]
thanks~~
