### ISSUE TITLE
support ripgrep

### ISSUE THREAD

**Issue by cvlmtg** [dyng/ctrlsf.vim#133]
would it be easy/possible to add support for ripgrep?

http://blog.burntsushi.net/ripgrep/

**Comment by dyng** [comment]
I feel a bit scared of so many grep-like tools... But I'll take a look at ripgrep, if `ripgrep` can output result with same format as `ag`, it should be not difficult to add it as a backend.

**Comment by cvlmtg** [comment]
yeah, there are a bit too many :D however the author claims his tools doesn't suffer from ag bugs on .gitignore, filename globs etc, and that's the reason I'd like to try it.
I might try to have a look at your code and see if I can help, but I've basically no knowledge of vimscript, so I make no promises :)

**Comment by dyng** [comment]
Actually I have made `ripgrep` support done :) Though it has not been merged into `master`. You can checkout `feature/ripgrep-support` branch and have an early taste.

p.s. `smartcase` is currently not supported. I'm waiting `ripgrep` updating its brew-installation.

**Comment by cvlmtg** [comment]
wow, thanks :)

I have a couple of days of holidays ahead, so the real tests on the field will begin wednesday. I'll report any bug here.

**Comment by cvlmtg** [comment]
Hi, i've started using it and it seems ok. smartcase doesn't work as you said, but I can make it work. I've installed ripgrep 0.2.1 today with its brew recipe and smartcase works with this little patch:

```
diff --git a/autoload/ctrlsf/backend.vim b/autoload/ctrlsf/backend.vim
index be87a6f..396c779 100644
--- a/autoload/ctrlsf/backend.vim
+++ b/autoload/ctrlsf/backend.vim
@@ -51,7 +51,7 @@ let s:backend_args_map = {
         \ },
     \ 'rg': {
         \ 'ignorecase': {
-            \ 'smartcase': '',
+            \ 'smartcase': '--smart-case',
             \ 'ignorecase': '--ignore-case',
             \ 'matchcase': ''
             \ },
```

I'll continue to test it

**Comment by cvlmtg** [comment]
I broke everything when I customized rg to my taste when used with the fish shell, but I quickly fixed it again. just in case it might be useful to other fish + vim users, here's my little function to use rg with the fish shell without breaking ctrlsf.vim

`.config/fish/functions/rg.fish`

```
function rg
  if isatty stdout
    command rg --smart-case --heading --pretty $argv | tr -d "\017" | less -R
  else
    command rg $argv
  end
end
```

tr is needed to strip some characters under tmux. see: https://medium.com/@crashybang/supercharge-vim-with-fzf-and-ripgrep-d4661fc853d2

**Comment by dyng** [comment]
Thanks, I'll add `--smart-case`.

**Comment by cvlmtg** [comment]
I've found no issues in my test, all the tasks I usually do worked without any difference with rg, so will you merge rg support in master? :)

**Comment by dyng** [comment]
Looks fine, let's merge it. :)

**Comment by cvlmtg** [comment]
🎉 🎉 

thanks :)

**Comment by lervag** [comment]
The before/after context options no longer works. It seems this may be due to different long option names.

**Comment by dyng** [comment]
I have fixed it, my thanks!

**Comment by lervag** [comment]
Thanks!
