### ISSUE TITLE
request: add word boundary search

### ISSUE THREAD

**Issue by cvlmtg** [dyng/ctrlsf.vim#141]
would it be possibile to have another command like <Plug>CtrlSFCwordPath/Exec which automatically adds word boundaries to the query?

**Comment by dyng** [comment]
Not a difficult thing that I have implemented in branch `feature/auto-word-boundary`, if you have time please have a try on it.

The new key mapping is `<Plug>CtrlSFCCwordPath/Exec`.

**Comment by cvlmtg** [comment]
I've been using this branch a while (with ripgrep), and it looks like it's working fine.

sometimes results looks a bit strange, but the problem is in the backed I suppose. If I search for "font" it doesn't find "fonts" but it finds "font-size". If I search for "font-size" it also finds "@header-font-size" etc.
that's a bit strange at first, but it's due to the fact that for vim a "word" depends on file type, while ripgrep has just one set of rules.

so I'd say well done 👍  😄

**Comment by dyng** [comment]
Actually I just wrap your search pattern with `\b`, and the rest things depend on your backend. But I'm not sure if it is what your want, and I'm not sure if this behavior is consistent in all backends.

I'll take a time to verify it and merge it.

**Comment by cvlmtg** [comment]
probably my previous comment wasn't clear. I said that what seemed strange at first in the results, instead makes sense because of the differencies between vim and the backend used.

Not sure about the consistency with other backends, but regarding "what I want" the results are a lot better now and much closer to what I expect.

probably the only option to make it better and more consistent would be to replace \b with custom word boundaries inside the regex, like: [^A-Za-z]word[^A-Za-z]. in the case of a css file, where "-" is considered part of a word, that regex should become [^A-Za-z-]word[^A-Za-z-] etc...
just the first idea that came to my mind at 9 in the morning without my coffee 😄  (e.g. numbers must be included? what about non-ascii letters? probably \W would be better, but do all the backends support that? etc)

**Comment by dyng** [comment]
Merged. Thanks for your comment!
