### ISSUE TITLE
Trying to define shortcuts

### ISSUE THREAD

**Issue by davegri** [dyng/ctrlsf.vim#142]
I have the following lines in my vimrc:
```
:nmap     <Leader>f <Plug>CtrlSFCwordPath
:vmap     <Leader>f <Plug>CtrlSFVwordPath
```

pressing <Leader>f does nothing, am I doing something wrong?

**Comment by dyng** [comment]
Can't confirm it, your command works well in my vim. Please make sure you have done the mapping correctly.

**Comment by davegri** [comment]
My bad, was defining shortcut before defining leader key, thanks
