### ISSUE TITLE
Folded results

### ISSUE THREAD

**Issue by davegri** [dyng/ctrlsf.vim#143]
It would be nice if all results were folded by default, and could be expanded one by one (or just entered directly from the name). or even just an option to only show the names of the results

**Comment by dyng** [comment]
I think what you want is an overview of results, am I right? Currently there is no fully functional overview window, but you can use `:lopen` to open a location list, which contains results in a more compact view.

**Comment by davegri** [comment]
A setting to simply hide the code and only show the filenames would be nice, any chance on getting that?

**Comment by dyng** [comment]
It's not possible currently because ctrlsf is not designed for that purpose.

If you want to limit searching in a specific directory or on a specific type of files, you can use path and `-filematch`, for example

```vim
" search your/dir
:CtrlSF foo your/dir

" search only java source
:CtrlSF -filematch '.*.java' foo
```
