### ISSUE TITLE
Add filetype support for rg

### ISSUE THREAD

**Issue by DaSea** [dyng/ctrlsf.vim#151]
For `rg`, after the line of 108 in file `autoload/ctrlsf/backend.vim`, add code:
```vim
" filetype (NOT SUPPORTED BY ALL BACKEND)
" support backend: ag, ack, rg
if !empty(ctrlsf#opt#GetOpt('filetype'))
  if runner ==# 'ag' || runner ==# 'ack'
     call add(tokens, '--' . ctrlsf#opt#GetOpt('filetype'))
  elseif runner ==# 'rg'
     call add(tokens, '--type '.ctrlsf#opt#GetOpt('filetype'))
   endif
endif
```
**can you add it? i have test it!**

**Comment by dyng** [comment]
It should be fine if you can create a pull request about your changes. I'll glad to merge it.

**Comment by DaSea** [comment]
@dyng 
ok, i have a pull request, can you merge it? thanks!

**Comment by dyng** [comment]
Merged. Thanks!
