### ISSUE TITLE
不支持搜索_build目录下面的文件？

### ISSUE THREAD

**Issue by dcy** [dyng/ctrlsf.vim#153]
你好！
我使用ctrlsf的时候发现ctrlsf不搜索_build目录下面的文件，能不能配置它_build目录下面的文件也可以被搜索？

**Comment by dyng** [comment]
@dcy 你好，请按照issue模板描述你的问题。现在你的issue缺少足够信息。

不过如果你使用的后端是`ag`或者类似的话，我猜测你可能`_build`目录包含在`.gitignore`文件内，`ag`默认不会搜索被git忽略的文件。

**Comment by dcy** [comment]
@dyng 谢谢，确实是```.gitignore``` 包含了```_build```,那么有什么办法让它可以搜索么？因为第三方库也在里面，有时想搜索第三方库的代码

**Comment by dyng** [comment]
@dcy 可以使用`g:ctrlsf_extra_backend_args`把`-u`参数传给`ag`。

**Comment by dcy** [comment]
```
let g:ctrlsf_extra_backend_args = {
    \ 'ag': '-u'
    \ }
```
谢谢，这样可以了
