### ISSUE TITLE
[feature request]: Use default key mapping for Quickfix mode

### ISSUE THREAD

**Issue by skamsie** [dyng/ctrlsf.vim#157]
First of all great plugin. I did not find any problems I just want to make a suggestion.

I use the Quickfix mode more often and it seems that there is only one way of opening the files in that mode, using <cr> (Enter).  I would like to be able to use the normal keys like in the CtrlSF window:

```
p - Like Enter but open file in a preview window.
P - Like Enter but open file in a preview window and switch focus to it.
O - Like Enter but always leave CtrlSF window opening.
T - Like t but focus CtrlSF window instead of new opened tab.
```

Thanks

**Comment by dyng** [comment]
Thanks for your good suggestion. First of all, I will explain why I have added `:CtrlSFQuickfix` command, quote from another related issue #154 .

> ...I'm curious about why you favor :CtrlSFQuickfix over :CtrlSF? I have added quickfix-serial commands because of a user request, but not so satisfied with it myself. Mostly because of its limited feature, inconsistent interface and I almost never have used it.

But so many users love `CtrlSFQuickfix`, I think there are some reasons that I don't know. Here are some possible reasons that I thought

- more compact view of results
- builtin commands for quickfix window
- plugins that enhance quickfix window
- a similar user experience of ack.vim

Can you tell me some reasons why you favor `CtrlSFQuickfix` over `CtrlSF`? I'll consider to provide a more useful, fully featured `CtrlSFQuickfix` alternative.

**Comment by skamsie** [comment]
Well to be completely honest someone introduced me to ack.vim, which only displays to quickfix. The biggest problem with ack, which stops me from using it is this bug: https://github.com/mileszs/ack.vim/issues/18 which the maintainer does not even consider fixing...

That is how I searched for alternatives and stumbled upon your plugin, which again I think it is great, but for me personally, the "Sublime like" view offers too much context which I don't really need...

**Comment by dyng** [comment]
If there is a command that you can switch result window between 'compact' view and 'normal' view, does that suffice your needs? (also an option lets you use compact view by default)

**Comment by skamsie** [comment]
I would like to be able to open a file in a preview window without the cursor jumping to it by pressing `p`, when using `:CtrlSFQuickfix`. That's all :)

**Comment by dyng** [comment]
Well, 'compact' ctrlsf window (not a quickfix window) will have all features of ctrlsf, including `p` for file preview.

But it will not be coming soon, so please be patient for it.

**Comment by dyng** [comment]
Close this issue as #159 is merged.
