### ISSUE TITLE
Using "q" fails with "E444: Cannot close last window"

### ISSUE THREAD

**Issue by christianrondeau** [dyng/ctrlsf.vim#165]
# Issue description

* When CtrlSF panel is whe main window, using <kbd>q</kbd> fails with `E444: Cannot close last window` *

## Things about your system and environment

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *Windows 20, Ubuntu 16 and Termux*        |
|   vim   | *Vim 7.4 (stock Ubuntu 16.04) and Vim 8.0.442* |
| backend |             *ag 1.0.2*              |
| locale  |            *en_US.UTF-8*             |

## Problem statement

I skipped the rest of the form because  I believe the issue to be self explanatory ; it is pretty much a feature request, more than a bug.

I use Vim with Termux on an Android phone, so the available screen real estate is very limited. I often work with only the CtrlSF panel, and when I'm done and I press `q`, it crashes with `E444: Cannot close last window`.

## Improvement suggestion

I suggest that we try/catch for `E444` and use `bdelete` if this is the last window. It'll bring the user back to their previous buffer, instead of throwing an error.

If you agree with my suggestion, I can provide a pull request.

**Comment by dyng** [comment]
I agree with your suggestion. Although it's rare that CtrlSF panel is the last window in the most cases, but your improvement can make CtrlSF more robust. Your pull request is really welcome :)

**Comment by christianrondeau** [comment]
Fixed by https://github.com/dyng/ctrlsf.vim/pull/167
