### ISSUE TITLE
 'No file has been changed.' meaning

### ISSUE THREAD

**Issue by sfahlberg** [dyng/ctrlsf.vim#169]
#### Issue description
awesome plugin! thanks for your work on it!

whenever I open CtrlSF, it says 'No file has been changed.' every time I'm not sure why. Is this expected behavior? I'd like to turn it off. What files are being changed. I looked at the code and couldn't figure out what it was doing 

#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       OS X El Capitan 10.11.6        |
|   vim   | Neovim 0.1.7 |
| backend |             ag version 1.0.2              |
| locale  |            *en_US.UTF-8*             |

**Comment by dyng** [comment]
'No file has been changed' is a warning message that is shown when you try to save current CtrlSF buffer, but no change is found.

I think it may be caused by a plugin conflict, can you disable ALL other plugins ant try again?

**Comment by sfahlberg** [comment]
strange- after doing some bisecting, I discovered the error was this line ```" inoremap <C-[> <ESC>:w<CR>``` `Ctrl [` is what I always use to escape and save. I just updated it to `inoremap <expr> <C-[> @% == '__CtrlSF__' ? 'unmap <C-[>' : '<ESC>:w<CR>'` and it appears to work now without that. Do you have a better solution?

**Comment by dyng** [comment]
Another solution is defining your own `g:CtrlSFAfterMainWindowInit` hook.

For example:

```
function! g:CtrlSFAfterMainWindowInit()
    inoremap <buffer> <C-[> <ESC>
endfunction
```
