### ISSUE TITLE
 针对某一个后缀名的搜索

### ISSUE THREAD

**Issue by hominlinx** [dyng/ctrlsf.vim#17]
是否支持只在.cpp中搜索一个单词 ？？ 谢谢

**Comment by dyng** [comment]
最新的v1.0已经部分支持这个功能，`:CtrlSF -filetype cpp foo`可以限定在`*.cpp`，`*.h`中进行搜索。

没有使用ag的`-G pattern`是因为ack将这个选项删除了，因此无法保证ctrlsf能够同时工作在ack/ag下。我再考虑一下这个问题应该如何解决。

**Comment by franckXu** [comment]
:CtrlSF -filetype css height 会报错：
Failed to call backend.error message:
Usage: ag [optinos] pattern [path]

其它文件没问题

**Comment by dyng** [comment]
从v1.4支持`-filematch`参数，推荐使用该参数来选定需要搜索的文件。

例如：

    :CtrlSF -filematch '\.css' pattern

**Comment by improve100** [comment]
需要刷选多个类型的时候怎么指定？
：CtrlSF -filematch '\.cpp \.hpp'

**Comment by dyng** [comment]
`filematch`用的是正则表达式

```vim
CtrlSF -filematch '\.(cpp|hpp)'
```
