### ISSUE TITLE
Support "git grep" as backend

### ISSUE THREAD

**Issue by mz026** [dyng/ctrlsf.vim#174]
Hi, thanks for building such awesome plugin!
Is it possible to config the backend as `git grep`?

**Comment by dyng** [comment]
Why do you prefer `git grep` over `ag`(or `pt`, `rg`)? They all search files under working directory, carefully ignore files matching patterns in `.gitignore`, and also in a faster speed.

**Comment by mz026** [comment]
Turns out it's an issue of [`ag` not respecting some patterns in `.gitignore`](https://github.com/ggreer/the_silver_searcher/issues/285). After tweaking my `.gitignore` it works fine. Thanks!!
