### ISSUE TITLE
Problem with autochdir and CtrlSF

### ISSUE THREAD

**Issue by lervag** [dyng/ctrlsf.vim#175]
# Issue description

Load Vim with the provided minimal vimrc file after you have created the test files described below:

1. `nvim -u minivimrc` (or `vim -u minivimrc`)
    This should open the `test/lorem` file and use CtrlSF to search for the word `ipsum`.

2. Hit enter.

3. Do `CtrlSFToggle`

4. Hit enter.

After the four above steps, we are now in an empty buffer. I would expect to be in the buffer corresponding to the `sub1/lorem` file.

# Minimal example

Minimal vimrc file: `minivimrc`

```vim
set nocompatible
let &runtimepath = '~/.vim/bundle/ctrlsf.vim,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/ctrlsf.vim/after'
filetype plugin indent on
syntax enable

set autochdir

silent edit ~/test/lorem

augroup Testing
  autocmd!
  autocmd VimEnter * CtrlSF ipsum
augroup END
```

Test files:

```
test
├── lorem
├── sub1
│   └── lorem
├── sub2
│   └── lorem
└── sub3
    └── lorem
```

Where `lorem` contains:

```
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

# System information

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *Arch Linux*        |
|   vim   | *neovim 0.2.0* and *vim 8.0.628* |
| locale  |            *en_US.UTF-8*             |

**Comment by dyng** [comment]
Appreciate your detailed and comprehensive issue description, thank you at first! :)

It's a problem caused by `autochdir`. I'll add an option that let user use absolute path instead, and automatically apply it if `autochdir` flag is on.

**Comment by dyng** [comment]
@lervag Please take branch `feature/absolute-path` and have a try. Feel free to report any problem here. Thanks!

**Comment by lervag** [comment]
Thanks, @dyng, this seems good. I'm curious, though: Is it possible to separate the actual path from the displayed path? That is, could you display the relative path while using the absolute path for "actions"?

**Comment by lervag** [comment]
I assume this would require some more updates, though, and it is not very important to me.

However:

```diff
-        return strpart(a:filename, i+strlen(getcwd())+1)
+        return fnamemodify(a:filename, ":.")
```
I would expect the above change to be sufficient for things to work. I'll give it a test on my end.

**Comment by lervag** [comment]
Ah, sorry. My last "However" is wrong, since the paths are not updated after toggling the search window. So, one solution could be to update the paths when toggling the search window. If that is not possible, and if it is not possible to separate the displayed path from the path that is used for the actions, then I guess absolute paths are the only option.

Note, though, that you might still be interested in using a more advanced relative path function. See e.g. [vimtex#path#relative](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/paths.vim#L18). This allows relative paths also for files that live beneath the current files.

**Comment by dyng** [comment]
> That is, could you display the relative path while using the absolute path for "actions"?

Not impossible I think. But there is a subtle fact related to displayed path is that the path will be recognized as "real path" when saving your editing, so you need to make sure displayed path is right in any situation.

> one solution could be to update the paths when toggling the search window.

It's also possible that re-rendering CtrlSF's content in every `BufEnter` event, but it's poor in performance and I think what we get from it can't cover the performance lost.

> See e.g. vimtex#path#relative. This allows relative paths also for files that live beneath the current files.

I replaced `fnamemodify(a:filename, ":.")` with `vimtex#path#relative` and invoked CtrlSf, but it stuck... I don't know why :(

**Comment by lervag** [comment]
> Not impossible I think. But there is a subtle fact related to displayed path is that the path will be recognized as "real path" when saving your editing, so you need to make sure displayed path is right in any situation.

I see, so saving the CtrlSF buffer will save to the displayed file names. Would it not be possible to e.g. create a simple map from the displayed paths to full paths and to use this? That is, when you create the content for the CtrlSF buffer, you create a dictionary where the keys are the displayed paths and the values are the actual full paths. Then, when you save the edits in the buffer, you could apply this map for the file names. I am not sure if this is possible, but if it is, then you could solve my issue while keeping the shortened paths. Everyone wins. :)

> I replaced fnamemodify(a:filename, ":.") with vimtex#path#relative and invoked CtrlSf, but it stuck... I don't know why :(

First, sorry, it should be `vimtex#paths#relative`, with an `s`. The syntax is:

```vim
function! vimtex#paths#relative(file, root)
```

That is, you want the relative path of `file` from `root`. Note that it assumes that none of the paths have `/` at the end.

**Comment by dyng** [comment]
I'm hesitating on the idea that a path looks like a relative path but not truly a relative path (because working directory can change and break the relative path).

I think it's not a big problem to solve this issue by using absolute path. But your pull request is welcome if you find a more elegant solution :)

**Comment by lervag** [comment]
My point is that the handling of paths form the CtrlSF point of view should _always_ be absolute. Using relative paths is convenient for the user for making it easy to read. But on the backend, the use of relative paths requires that you have "full control" on the current directory, which you don't have (e.g. due to things like `autochdir`).

The same issue as here will happen for people who, for some reason, changes their current directory manually when CtrlSF has been opened first with some `getcwd()`. By using only absolute paths in the backend, you will evade this issue completely.

However, I do recognize the burden it may be to update the code as I suggest. It might not be worth the gain (at least not for you). And I can live with the current behavior where absolute paths are used (and displayed) if `autochdir` is set.

**Comment by dyng** [comment]
Ok, I have got your point and agreed that using absolute path internally can avoid many problems related to working directory change.

But like you said, I have not so much time to make such an improvement, I'm sorry about that.

**Comment by lervag** [comment]
No problem. I might consider to try to implement it and open a PR, if I should get the time. In any case, thanks for fixing the issue! :+1:

**Comment by dyng** [comment]
You are welcome :) Thanks for your detailed issue and helpful suggestion!

**Comment by lervag** [comment]
Again, no problem, and thanks for your great plugin! :)

**Comment by omriperi** [comment]
anything new with that request? maybe someone added the enhancement?
