### ISSUE TITLE
Preview with mouse click

### ISSUE THREAD

**Issue by MichaelAquilina** [dyng/ctrlsf.vim#181]
I cannot tell if this is a supported feature, but after reading the docs and not finding anything I thought it might be worth posting an issue here in case it was not supported:

Is it possible to open results in a preview with e.g. ctrl + left mouse click? If not, would adding support for it be hard?

**Comment by dyng** [comment]
You can do it by customizing your own mapping:

```vim
let g:ctrlsf_mapping = {
    \ "popen": "<C-LeftMouse>"
    \ }
```

**Comment by MichaelAquilina** [comment]
Argh sorry about that, should have looked harder. Thanks for the help though!

**Comment by dyng** [comment]
@MichaelAquilina Never mind :)
