### ISSUE TITLE
if ctrlsf quit with esc, when I press <Up> or <Down> , it will be A B

### ISSUE THREAD

**Issue by jacky1193610322** [dyng/ctrlsf.vim#187]
*If I map esc to quit, it works, but when I open the ctrlsf result list, then I press key Up and Down,
if will quit the ctrlsf and insert A B*
I got the result list
![image](https://user-images.githubusercontent.com/16514353/29992920-e42d4fa6-8fd9-11e7-94fa-6671ebf7127c.png)
then I want to up and down, I can use jk, it works, but if I use the key Up and Down
it will close the ctrlsf window, and insert A and B
![image](https://user-images.githubusercontent.com/16514353/29992928-28922e5a-8fda-11e7-8b36-37e2766637c7.png)

#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *OS X EI Capitan*        |
|   vim   | *Vi IMproved 8.0 Included patches: 1-704* |
| backend |             *ag version 2.0.0*              |
| locale  |            *zh_CN.UTF-8*             |

- vimrc:

    ```vim
    " ctrlsf {{{
    let g:ctrlsf_position = 'bottom'
    let g:ctrlsf_ackprg = '/usr/local/bin/ag'
    let g:ctrlsf_winsize = '30%'
     "let g:ctrlsf_extra_backend_args = {
     "   \ 'ag': '-l --nocolor  -g'
     "   \ }
    let g:ctrlsf_auto_close = 1
    let g:ctrlsf_confirm_save = 0
    " Note: cannot use <CR> or <C-m> for open
    " Use : <sapce> or <tab>
    let g:ctrlsf_mapping = {
        \ "open"  : "<CR>",
        \ "openb" : "",
        \ "tab"   : "t",
        \ "tabb"  : "T",
        \ "prevw" : ["<Space>", 'p'],
        \ "quit"  : ["q", "<Esc>"],
        \ "next": "n",
        \ "prev": "N",
        \ "pquit" : ["<Esc>", "q"],
        \ }
       " }}}

    ```

**Comment by dyng** [comment]
Sorry for this late reply.

Actually it is not an issue about ctrlsf but vim itself. Please refer below link.

https://www.cyberciti.biz/faq/howto-fix-vim-up-down-keys-inserting-a-b-c-d-character-on-remote-ssh-session/

**Comment by jacky1193610322** [comment]
谢谢你的回复，我试了Solution 2和3，但是还是没有用，我上面提到的按上下键出现AB的情况，只有在我配置了ctrlsf quit的退出键为<Esc>的时候才会出现这个问题， 如果我不这样配置，就一切正常。我在中国，之前看你在回复别人信息的时候，使用中文，所以这里使用中文描述，会清晰一点，不知道你有没有解决方法？

**Comment by dyng** [comment]
你先确认上下键有没有被映射成为其他键，可以用`map <UP>`和`imap <UP`来看。

然后禁用其他插件，看是否是ctrlsf以外插件的问题。

然后你用GUI的vim再来看一下会不会有这个问题，我在终端下的vim也有同样的问题，但是macvim就没有问题。

**Comment by jacky1193610322** [comment]
谢谢你的回复，我会尝试一下，到时候在回复你
