### ISSUE TITLE
Regex error when try open file in windows system

### ISSUE THREAD

**Issue by wangchunsen** [dyng/ctrlsf.vim#192]
I try open a file by press enter key in search result window, but only got an error. 
It's because my file path contains `\_ ` ,like `\xxx\_path.xml`.

**Comment by dyng** [comment]
请打开 debug 模式（`let g:ctrlsf_debug_mode = 1`），并把错误信息贴在这里，谢谢。

**Comment by dyng** [comment]
抱歉，因为我没有 windows 无法测试。请更新至分支`fix/unnecessary-regex`代我测试一下，谢谢。
