### ISSUE TITLE
Run CtrlSF failed with index out of range error after fail to open directory

### ISSUE THREAD

**Issue by spacewander** [dyng/ctrlsf.vim#195]
The full error message is:
```
Error detected while processing function ctrlsf#Search[15]..<SNR>154_ExecSearch[26]..<SNR>154_OpenAndDraw[2]..ctrlsf#win#Draw[1]..ctrlsf#view#Render[2]..<SNR>169_NormalView[7]..<SNR>169_Summary[1]..ctrlsf#db#FileResultSet[5]..ctrlsf#db#FileResultSetBy:
line   13:
E684: list index out of range: -1
E116: Invalid arguments for function add
Error detected while processing function ctrlsf#Search[15]..<SNR>154_ExecSearch[26]..<SNR>154_OpenAndDraw[2]..ctrlsf#win#Draw[1]..ctrlsf#view#Render[2]..<SNR>169_NormalView:
line    7:
E712: Argument of extend() must be a List or Dictionary
```

Maybe you could reproduce the issue with the case above:
1. create a directory which is unavailable to open.
```
$ ls -l
drw------- 2 root root 4.0K 12月 18 23:36 test
-rw-r--r-- 1 lzx  lzx     2 12月 18 23:36 test.txt
```
2. running `ag` will get result like this:
```
 $ ag "a"
ERR: Error opening directory ./test: Permission denied
test.txt
1:a
```
3. run `CtrlSF` inside test.txt, the error occurs. 

Looks like the error is caused by https://github.com/dyng/ctrlsf.vim/blob/master/autoload/ctrlsf/db.vim#L38.

**Comment by dyng** [comment]
严格来说这是一个`rg`（或`ag`）的bug（或者说是特性）。

首先原因和**文件是否有权限**没有关系，主要是结果的输出格式在**搜索目录**和**搜索单一文件**时是不一样的。

搜索目录时

```
$ rg -C 3  --smart-case --fixed-strings --no-heading --color never --line-number -- 'a' '/private/tmp/testctrlsf'
/private/tmp/testctrlsf/a.txt: Permission denied (os error 13)
/private/tmp/testctrlsf/b.txt:1:a
/private/tmp/testctrlsf/b.txt-2-b
/private/tmp/testctrlsf/b.txt-3-c
/private/tmp/testctrlsf/b.txt-4-d
```

搜索文件时

```
$ rg -C 3  --smart-case --fixed-strings --no-heading --color never --line-number -- 'a' '/private/tmp/testctrlsf/b.txt'
1:a
2-b
3-c
4-d
```

可以看到搜索单一文件时，输出结果中没有文件路径，这就导致了解析结果出错。

解决方法也比较简单，就是在解析单一文件时，自己补上文件路径，而不依赖输出的结果。只是最近实在没有时间来 fix 这个问题……不知道你能不能帮忙 fix 一下？

**Comment by spacewander** [comment]
@dyng 
可惜我的 Vimscript 水平只够配配 vimrc，编写插件还是不够用的……
目前我这边的绕过办法就是注释掉越界的那一行。

**Comment by wsdjeg** [comment]
I like this plugin， and I will fix it tonight

/cc  TODO

**Comment by wsdjeg** [comment]
我看了下backend，

ag 选项需要加：

```
    --[no]filename
              Print file names. Enabled by default, except when searching a
              single file.
```

rg 晚上晚些时候我再看看

**Comment by kristijanhusak** [comment]
@dyng i'm getting this same error now after the commit where you added the `--filename` part. I tried checking out to the older commits and everything works fine.

**Comment by dyng** [comment]
Oops, maybe the latest commit breaks something, I’ll take a look soon.

**Comment by bogdan0083** [comment]
Can confirm that plugin stopped working after the last update. Getting exactly the same error as the topic starter.

**Comment by wsdjeg** [comment]
sorry，I will take a look.

**Comment by dyng** [comment]
A hotfix patch is applied. Sorry for inconvenience. @kristijanhusak @bogdan0083 

Actually it is a bug of `ag`, it does not work like what its manual says.

**Comment by wsdjeg** [comment]
@dyng I recommend to use `rg` instead. :)

**Comment by bogdan0083** [comment]
It works like a charm now, thanks! :heart:
