### ISSUE TITLE
E16 error when quit from CtrlSF

### ISSUE THREAD

**Issue by Yggdroot** [dyng/ctrlsf.vim#199]
#### Issue description

```
Error detected while processing function
ctrlsf#Quit[6]..<SNR>100_Quit[2]..ctrlsf#win#CloseMainWindow[12]..ctrlsf#win#FocusCallerWindow[2]..ctrlsf#win#FocusWindow:
line   11:
E16: Invalid range: 2wincmd w
```

- vimrc:
nothing

Steps to reproduce:
1. open a file `test.txt` with vim
2. open NerdTree(or tagbar or something) on the left of `test.txt` window.
3. use CtrlSF to search something
   now the windows from left to right are CtrlSF window, NerdTree window and test.txt window.
4. close NerdTree window
5. quit from CtrlSF window using `q`
6. the error occurs

**Comment by dyng** [comment]
这是因为ctrlsf在打开窗口前会记住光标所在的窗口id，并在关闭ctrlsf窗口时把光标切到打开ctrlsf时光标所在窗口。

但是因为你在打开ctrlsf窗口**后**，关闭了NerdTree窗口，就导致之前记住的窗口id不正确了。

一时没想到很好的办法，你有没有什么建议？

**Comment by Yggdroot** [comment]
你使用的是`winnr()`, 不是`win_getid()`, winnr会变，winid不会变，可以记录winid，跳转的时候转成winnr。
