### ISSUE TITLE
可以给compact模式和normal模式分别指定g:ctrlsf_auto_close吗

### ISSUE THREAD

**Issue by Yggdroot** [dyng/ctrlsf.vim#200]
我的使用习惯是希望normal模式可以auto close, 而在compact模式，不用auto close，就像quickfix window。

**Comment by dyng** [comment]
我觉得这个建议挺好的，可以作为auto close的默认行为。要让用户可以分别指定compact模式和normal模式的行为，我觉得可以扩展`g:ctrlsf_auto_close`的格式。

不过很不好意思，因为最近已经很少使用vim，实在没时间再进行这些开发。看到你的vim script挺好的，很欢迎提出pull request :)
