### ISSUE TITLE
内容格式与view mode不匹配

### ISSUE THREAD

**Issue by Yggdroot** [dyng/ctrlsf.vim#204]
用CtrlSF查找某个字符串，窗口是normal mode，按M切换到compact mode，这时再查找一个字符串，在compact mode的窗口里内容格式变为normal mode里的格式，而应为compact mode的格式。

如果default mode是compact mode，应该也有相应的错误。

**Comment by dyng** [comment]
我在 #205 里修复了这个问题（以及 #199 ），请试下有没有问题。
