### ISSUE TITLE
Feature for accept custom locations

### ISSUE THREAD

**Issue by chemzqm** [dyng/ctrlsf.vim#210]
The LSP server or some kind of smart engine could give me a location list for references, I'm wondering if I could pass this list to ctrlsf.vim and let user do replacement in the buffer of ctrlsf

**Comment by dyng** [comment]
I think ctrlsf is **NOT** designed for that purpose. But as it can accept any input which conforms to the format of `Ack`'s result, it is *possible* if you ask, although you need to implement it with coding some vim script.

**Comment by chemzqm** [comment]
Ok, I could just use some code from ctrlsf to make it works.
