### ISSUE TITLE
Helptags generating is failed after an update

### ISSUE THREAD

**Issue by unclechu** [dyng/ctrlsf.vim#213]
Commit: 67ea96fe20ad6d87e75980af105d272f7e4728ad
```text
[dein] Error generating helptags:
[dein] Vim(helptags):E154: Duplicate tag ":CtrlSFStop" in file /home/uc/.cache/nvim-dein-plugins/.cache/init.vim/.dein/doc/ctrlsf.txt
[dein] function <lambda>1[1]..dein#install#_polling[1]..<SNR>220_install_async[9]..<SNR>220_done[7]..dein#install#_recache_runtimepath[20]..<SNR>220_helptags,
line 12
```
Here's the clashing:
https://github.com/dyng/ctrlsf.vim/blob/67ea96fe20ad6d87e75980af105d272f7e4728ad/doc/ctrlsf.txt#L170
https://github.com/dyng/ctrlsf.vim/blob/67ea96fe20ad6d87e75980af105d272f7e4728ad/doc/ctrlsf.txt#L183

**Comment by dyng** [comment]
Fixed. Thanks for your bug report.
