### ISSUE TITLE
"E117: Unknown function setbufline" after update ctrlsf to v2.0.1

### ISSUE THREAD

**Issue by Yggdroot** [dyng/ctrlsf.vim#215]
#### Issue description

![qq 20180625133825](https://user-images.githubusercontent.com/2705841/41832098-145f3888-787d-11e8-9560-43b4d2c870b0.png)

I am using vim8.0.692, I encounter an error after update ctrlsf to v2.0.1.
I find `setbufline` was fist introduced by patch 8.0.1039, so it means that if I want to use the async feature, I have to update vim to 8.0.1039+?

**Comment by dyng** [comment]
Yes, please update your vim to the latest version. But I think an user-friendly warning may be better than a system error, I'll add it soon.

**Comment by Yggdroot** [comment]
Perhaps it's better to point it out in readme.

**Comment by dyng** [comment]
@Yggdroot good idea, I'll also add it.
