### ISSUE TITLE
Error detected while processing function ctrlsf#Search:

### ISSUE THREAD

**Issue by caoyudeng** [dyng/ctrlsf.vim#218]
## Before submitting your issue（请在提交 issue 前一定要检查以下项目！）

1. Update to the latest version of CtrlSF.
2. Update your backend(ag/ack/pt/rg) to their latest version.
3. Enable debug mode to try to find what is going wrong yourself. You can enable debug mode by `let g:ctrlsf_debug_mode = 1`.

If you can't find out why things do not work or can be sure it's a bug of CtrlSF, please fulfill below issue template. Thanks in advance!

#### Issue description

输入：CtrlSF leader 报错
Error detected while processing function ctrlsf#Search..<SNR>66_ExecSearch..<SNR>66_DoSearchSync..<SNR>66_OpenAndDraw..<SNR>66_Open..ctrlsf#win#OpenMain
Window:
line    2:
E117: Unknown function: win_getid
E15: Invalid expression: { 'bufnr' : bufnr('%'), 'winid' : win_getid(winnr()), }

#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *CentOS Linux release 7.4.1708 (Core)*        |
|   vim   | *VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  2 2017 00:45:39)Included patches: 1-160* |
| backend |             *ack 2.22*              |
| locale  |            *en_US.UTF-8*             |

- log:

Tokens: ['leader']
ParsedResult: {'pattern': 'leader'}
Options: {'pattern': 'leader', '_vimregex': '\V\cleader', '_vimhlregex': {'normal': '\V\c\(\^\d\+:\.\*\)\@<=leader', 'compact': '\V\c\(|\d\+ col \d\+|\.\*\)\@<=leader'}}
Tokens: ['-C', '3']
ParsedResult: {'context': 3}
ExecCommand: ack -C 3  --smart-case --literal --noheading --nogroup --nocolor --nobreak --nocolumn --with-filename -- 'leader' '/home/cyd/git_repositor/Server'
Errors reported by backend:
Error detected while processing function ctrlsf#Search..<SNR>66_ExecSearch..<SNR>66_DoSearchSync..<SNR>66_OpenAndDraw..<SNR>66_Open..ctrlsf#win#OpenMainWindow:
line    2:  
E117: Unknown function: win_getid
E15: Invalid expression: { 'bufnr' : bufnr('%'), 'winid' : win_getid(winnr()), }  

- vimrc:

"                                                                                                                                                       
" A (not so) minimal vimrc.
"

" You want Vim, not vi. When Vim finds a vimrc, 'nocompatible' is set anyway.
" We set it explicitely to make our position clear!
set nocompatible

filetype plugin indent on  " Load plugins according to detected filetype.
syntax on                  " Enable syntax highlighting.

set autoindent             " Indent according to previous line.
set expandtab              " Use spaces instead of tabs.
set softtabstop =4         " Tab key indents by 4 spaces.
set shiftwidth  =4         " >> indents by 4 spaces.
set shiftround             " >> indents to next multiple of 'shiftwidth'.

set backspace   =indent,eol,start  " Make backspace work as you would expect.
set hidden                 " Switch between buffers without having to save first.
set laststatus  =2         " Always show statusline.
set display     =lastline  " Show as much as possible of the last line.

set showmode               " Show current mode in command-line.
set showcmd                " Show already typed keys when more are expected.

set incsearch              " Highlight while searching with / or ?.
set hlsearch               " Keep matches highlighted.

set ttyfast                " Faster redrawing.
set lazyredraw             " Only redraw when necessary.

set splitbelow             " Open new windows below the current window.
set splitright             " Open new windows right of the current window.

set cursorline             " Find the current line quickly.
set wrapscan               " Searches wrap around end-of-file.
set report      =0         " Always report changed lines.
set synmaxcol   =200       " Only highlight the first 200 columns.

set list                   " Show non-printable characters.

set number
set tags=./.tags;,.tags

" za : open/close current fold 
" zM : close all
" zR : open all
"set foldmethod=indent
set foldmethod=syntax
set nofoldenable

if has('multi_byte') && &encoding ==# 'utf-8'
  let &listchars = 'tab:▸ ,extends:❯,precedes:❮,nbsp:±'
else
  let &listchars = 'tab:> ,extends:>,precedes:<,nbsp:.'
endif

" The fish shell is not very compatible to other shells and unexpectedly
" breaks things that use 'shell'.
if &shell =~# 'fish$'
  set shell=/bin/bash
endif

" Put all temporary files under the same directory.
" https://github.com/mhinz/vim-galore#handling-backup-swap-undo-and-viminfo-files

" plug list

call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'}
Plug 'junegunn/fzf', {'dir':'~/.fzf', 'do':'./install --all'}
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
" Plug 'Valloric/YouCompleteMe'

".vim/bundle/vim-cpp-enhanced0highlight/after/syntax/cpp.vim 
"example : syntax keyword cppSTLtype initializer_list
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'derekwyatt/vim-fswitch'

Plug 'majutsushi/tagbar'

Plug 'dyng/ctrlsf.vim'

call plug#end()

" map key
let mapleader=";"
" file system
nnoremap <leader>fs     :NERDTree<CR>
" search system
nnoremap <leader>ss     :FZF<CR>
" .h .cpp switch
nnoremap <leader>sw     :FSHere<CR>
" tag list 
nnoremap <leader>tl     :TagbarToggle<CR>

" tagbar config
let tagbar_left=1
let tagbar_width=32
let g:tagbar_compact=1

" ctrlsf config
"let g:ctrlsf_debug_mode=1

" nerdtree config
"let nerdtree_left=0              

- file:

.vimrc

**Comment by dyng** [comment]
Seems `win_getid()` function is not implemented in your Vim. Please update your Vim to latest version.
