### ISSUE TITLE
三个问题

### ISSUE THREAD

**Issue by kdurant** [dyng/ctrlsf.vim#22]
1. 搜索结果的窗口，最好也可以设置在下面
2. windows下，文件结束符设置为dos时，搜索结果会显示讨厌的换行符，你懂是什么的
3. 最好搜索的目录可以是项目的根目录，就像**ctrlp**一样，会默认**.git**作为根目录，或者自己设置一个标记。不支持项目搜索会有很大的局限性。毕竟当前目录可能没有多少文件

**Comment by dyng** [comment]
谢谢你的建议。

1. 技术上倒没什么问题，主要我懒一直没有加（因为始终觉得上下分割压缩了本就紧张的可视区域）。如果你有兴趣的话，欢迎提出pull request。
2. ctrlsf只是ag（或者ack）的一个前端而已，只负责展示ag（或者ack）的搜索结果，所以你说的换行符可能是后端输出的结果（我不太清楚你的后端是ag还是ack）。如果希望在ctrlsf层改善这一点的话，可以加入对input的过滤。
3. 同上，ctrlsf主要目的是前端，所以搜索目录也主要交给后端控制。**ag默认是搜索vcs根目录的。**当然ctrlsf也可以像ctrlp一样自己实现对vcs根目录的搜索，然后传给后端。

诚如你所言，改进的余地还是很大的。不过我最近用vim的机会已经少了很多，动力不是很足，而且最重要的是**vimscript太难写了**。

**Comment by kdurant** [comment]
悲剧

**Comment by TossShinHwa** [comment]
设置搜索结果位置 +1, 顺便能设置窗口所占高度/宽度就更好了.

**Comment by dyng** [comment]
@kdurant @TossShinHwa 

已在 #23 中实现，配置文档请参考最新的README。
