### ISSUE TITLE
Doesn't recognize git worktree project

### ISSUE THREAD

**Issue by demon386** [dyng/ctrlsf.vim#220]
Git worktree is a "view" into a repo and the ".git" file is a regular file instead of a directory, whose content pointing to the main directory.

See doc: https://git-scm.com/docs/git-worktree

Right now ctrlsf seems to not recognize git worktree based project.

**Comment by dyng** [comment]
Sorry for this late reply. I'll support it in the next release.

**Comment by demon386** [comment]
Thanks!

**Comment by dyng** [comment]
Fixed in branch `fix/minor-fixes`, please have a try on it. And report any issue here.

**Comment by demon386** [comment]
Tested and it's working well. Much appreciated!
