### ISSUE TITLE
在 CtrlSF 中预览过后运行 only 会报错

### ISSUE THREAD

**Issue by skywind3000** [dyng/ctrlsf.vim#226]
这是个很常见的操作，预览过后用 c-w c-o 就出错：

![ctrlsf-3](https://user-images.githubusercontent.com/3035071/42019452-cc016ff8-7ae7-11e8-8b53-85fdd01666d2.png)

1. 打开 `.vimrc` 配置文件，切换到 `.vimrc` 所在目录
2. 运行：`CtrlSF noremap`
3. 在结果窗口里按 p 预览某结果。
4. 关闭当前搜索结果窗口，焦点回到 vimrc 文件窗口，但是预览窗口还留着
5. 在 vimrc 窗口 CTRL+W CTRL+o 或者执行 `:only` 命令，出现报错。

**Comment by dyng** [comment]
嗯 是个bug。之前因为假定用户一定是按`q`键来关闭窗口，现在看来还需要处理手动关闭窗口的情况。

**Comment by dyng** [comment]
在 `fix/minor-fixes` 分支已修复，请试用一下。

**Comment by skywind3000** [comment]
经过验证，没这个问题了。

**Comment by dyng** [comment]
Fixed in #228
