### ISSUE TITLE
建议：项目文件标志

### ISSUE THREAD

**Issue by skywind3000** [dyng/ctrlsf.vim#229]
项目标志能不能增加一个 `.root` 文件，再最开头：

1. 有些项目不在任何仓库里，我想新建个 .root 文件，让 ctrlsf 可以识别项目目录。
2. 有些项目在仓库里，但是仓库很庞大，我只想改其中某个子目录，我放个空的 .root 文件，能不能让 ctrlsf 识别到？

**Comment by dyng** [comment]
嗯，我觉得这个 feature 可以有。不过 `.root` 这个名字有点大，我觉得还是局限一些，用 `.ctrlsf_root` 吧。

不过明天要出差，可能一时没时间搞……看过你的 `asyncrun.vim` 项目，觉得你的 vimscript 应该挺好的，很欢迎提 pull request 😄

**Comment by dyng** [comment]
我现在想了想，觉得可以做成和 Leaderf 一样，是用户可配置的，这样就可以允许用户复用已有的 root marker，如何？

**Comment by skywind3000** [comment]
那太好了，但是你目前的规则有问题，你是先用.git文件名向上搜索，直到碰到根目录，再用.svn向上搜索，这是深度优先；应该广度优先才对，就是每一级目录搜索一般所有标志，没有再往上回溯。

举个例子，假设我写c，希望识别makefile文件名或者cmakelist.txt，但是我没有理解错的话，你优先搜索的规则容易跳过这些我需要的标志，定位到更上层目录的.git文件去。

最后是CtrlSF命令后面能不能支持下叹号，默认用当前目录搜索，加了叹号用项目目录搜索？这样可以同时使用两种方法。

**Comment by dyng** [comment]
嗯，之前的场景比较简单，几种 vcs 的目录基本是互斥的，所以用了深度优先搜索。现在看来，确实还是广度优先比较正确，我之后改一下。

关于用叹号来控制搜索路径的这个用法我觉得有点隐晦，个人不是太喜欢……搜索当前目录可以手动指定`.`，和多写一个叹号感觉也差不多。我觉得还是先维持现状吧，如果之后提出这个需求的用户多了，可以考虑增加一个参数。

**Comment by dyng** [comment]
@skywind3000 实现了，试试看有没问题？🙂

**Comment by skywind3000** [comment]
帅！
