### ISSUE TITLE
建议：增加在CtrlSF的Window中直接打开文件

### ISSUE THREAD

**Issue by griffinqiu** [dyng/ctrlsf.vim#231]
有时候在整个项目中搜索出结果，只需要处理一次。往往这个时候只需要找到匹配项后即可。

能不能在CtrlSF window增加一个快捷键，即
在CtrlSF的结果window中打开。

**Comment by dyng** [comment]
在 #161 #115 有人提到过，因为改动量比较大，暂时还没有实现的计划，抱歉。
