### ISSUE TITLE
Add <Plug> mappings instead of default mappings (like p, q, <C-j> etc)

### ISSUE THREAD

**Issue by bokwoon95** [dyng/ctrlsf.vim#232]
Thanks for your plugin 😄. I usually use `<C-j>` & `<C-k>` like so:

    nnoremap <C-j> 5gj
    nnoremap <C-k> 5gk

But right now `<C-j>` & `<C-k>` are default-mapped like this (as mentioned in the docs):

    <C-J>          Move cursor to next match.
    <C-K>          Move cursor to previous match.

Is it possible to change those default maps into `<Plug>` maps instead so that I can map them to `<C-n>` & `<C-p>`?

**Comment by dyng** [comment]
You can config your own mapping by using `g:ctrlsf_mapping`.
