### ISSUE TITLE
<Plug>CtrlSFCCwordExec (word boundary search) always produces empty results

### ISSUE THREAD

**Issue by kodemeister** [dyng/ctrlsf.vim#235]
Hi @dyng,

Thank you for your hard work done here! I switched from vim-grepper once CtrlSF got an asynchronous searching and it works great. I only have a minor trouble with searching whole words.

#### Issue description

Steps to reproduce:

1. Map `<Plug>CtrlSFCCwordExec` to `<Leader>*`.
2. Open a text file attached below, place the cursor on word `foo`  and press `<Leader>*`.

Expected: CtrlSF finds all occurrences of whole word `foo` in all files.
Observed: CtrlSF produces empty results (0 matched lines across 0 files. Done!).

Running `:CtrlSF -R -I "\bfoo\b"` also produces empty results.

However manual invocation of rg from terminal (directly copied from debug log) works fine:

```
$ rg -C 3  --ignore-case  --no-heading --color never --line-number -H -- "\bfoo\b" "/home/kodemeister/test"
/home/kodemeister/test/test.txt:1:foo
/home/kodemeister/test/test.txt-2-bar
/home/kodemeister/test/test.txt-3-baz
/home/kodemeister/test/test.txt-4-qux
/home/kodemeister/test/test.txt-5-quux
/home/kodemeister/test/test.txt-6-quuz
/home/kodemeister/test/test.txt-7-foobar
/home/kodemeister/test/test.txt:8:foo
/home/kodemeister/test/test.txt-9-bar
/home/kodemeister/test/test.txt-10-baz
```

Running simple `:CtrlSF -R -I "foo"` works fine as well but obviously it isn't limited with word boundaries.

#### Things about your system and environment

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *Arch Linux*        |
|   vim   | *Vim 8.1 Included patches: 1-22* |
| backend |             *ripgrep 0.8.1*              |
| locale  |            *en_US.UTF-8*             |

- log:

```
Tokens: ['-R', '\bfoo\b']
ParsedResult: {'pattern': '\bfoo\b', 'regex': 1}
Options: {'pattern': '\bfoo\b', 'regex': 1, '_vimregex': '\v\c(<|>)foo(<|>)', '_vimhlregex': {'normal': '\v\c(^\d+:.*)@<=(<|>)foo(<|>)', 'compact': '\v\c(\|\d+ col \d+\|.*)@<
=(<|>)foo(<|>)'}}
ExecCommand: rg -C 3  --ignore-case  --no-heading --color never --line-number -H -- "\bfoo\b" "/home/kodemeister/test"
TimerStarted: id=2
HighlightRegex: \v\c(^\d+:.*)@<=(<|>)foo(<|>)
ChannelClose
ConsumeResult: size=0
StopTimer: id=2
ParseFinish
```

- vimrc:

```vim
call plug#begin('~/.vim/plugged')
Plug 'dyng/ctrlsf.vim'
call plug#end()

let g:ctrlsf_case_sensitive = 'no'
nmap <Leader>* <Plug>CtrlSFCCwordExec
```

- file:

```
foo
bar
baz
qux
quux
quuz
foobar
foo
bar
baz
```

Thanks in advance!

**Comment by dyng** [comment]
First off, thanks for your clean issue description!  I'm not sure if this issue has anything to do with async searching, could you use sync search mode and try it again?

**Comment by kodemeister** [comment]
I've added `let g:ctrlsf_search_mode = 'sync'` to my vimrc and the search works now! There are multiple lines starting with `DefactorizeLine: [Factor]:` in the debug log. Their content is correctly loaded into the result pane. If I set `g:ctrlsf_search_mode` back to `'async'` then search fails as before.

I've also tried another backend (ag) but the results are pretty the same: works in sync mode, doesn't work in async mode. I'll use sync mode as a temporarily workaround.

**Comment by dyng** [comment]
@kodemeister Should be fixed in #236 . Please check out that branch and take a try!

**Comment by kodemeister** [comment]
Thank you very much, @dyng! The branch works like a charm! I believe we can merge it if the escaping doesn't cause any other issues.

**Comment by dyng** [comment]
Merged, thanks for your bug reporting!

**Comment by Hyvi** [comment]
i use the master branch, but it does not work in my imac. 

i add let g:ctrlsf_search_mode = 'sync' to my vimrc, then it works.

**Comment by dyng** [comment]
@Hyvi please create a new issue and follow the issue template.
