### ISSUE TITLE
windows backslash problem

### ISSUE THREAD

**Issue by sarrow104** [dyng/ctrlsf.vim#238]
## Before submitting your issue（请在提交 issue 前一定要检查以下项目！）

1. Update to the latest version of CtrlSF.
2. Update your backend(ag/ack/pt/rg) to their latest version.
3. Enable debug mode to try to find what is going wrong yourself. You can enable debug mode by `let g:ctrlsf_debug_mode = 1`.

If you can't find out why things do not work or can be sure it's a bug of CtrlSF, please fulfill below issue template. Thanks in advance!

#### Issue description

*You can describe your issue here.（请将你的 issue 内容填写于此）*

:CtrlSF some-key-words

之后，显示出来的路径，是双斜杠。

然后使用各种打开的快捷键，都会额外生成一个buffer——貌似被认为是网络资源，而不是本地资源。

#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *win10*        |
|   vim   | *gvim8.1.1* |
| backend |             *ag 2.1.0*              |
| locale  |            *zh_ZH.cp936*             |

- log:

    ```vim
no log
    :redir END
    ```

- vimrc:

    ```vim
very simple as nothing; just some key binding
    ```

- file:

    ```shell
    # please tell me something about files that CtrlSF doesn't work on.
    # if the content of file is private information, its encoding should be helpful.
    # it's important in some case!
    name: ctrlsf/plugin.vim
    encoding: utf-8
    content:
    # your file's content is here.
    ```

**Comment by dyng** [comment]
你的 issue 描述过于简短，缺少对 debug 有益的信息，请补充 日志（必需），截图（必需）或者动画（可选）。参考 #227 。

如何获取日志

1. 输入命令 `let g:ctrlsf_debug_mode = 1` 打开 debug 模式。
2. 执行命令 `CtrlSF something`，这时候日志就会打印到前台，复制出来。
2. 如果日志无法复制，也可以使用命令 `redir > D:\ctrlsf.log` 把日志输出到 `D:\ctrlsf.log` 文件。
