### ISSUE TITLE
Request: Search in symbolic link folders

### ISSUE THREAD

**Issue by tubecube** [dyng/ctrlsf.vim#239]
Could you please add a feature to search in symbolic link folders, like ctrlp option "g: ctrlp_follow_symlinks" ?

**Comment by dyng** [comment]
Could you give me a solid example (with debug logs is preferred) ? I don't know whether ctrlsf is not following symlinks or the backends is.

**Comment by tubecube** [comment]
When I open vim here and ctrlsf something existed in the "work" directory, it won't work, since "work" is a symlink. However I can find files by ctrlp here if I turn on the "g: ctrlp_follow_symlinks"  option. so I request a feature to follow symlinks, thanks. 
![image](https://user-images.githubusercontent.com/15215299/43685168-8057f3c6-98e0-11e8-9860-364470119c4c.png)

**Comment by ErichDonGubler** [comment]
Backends normally follow the symlinks -- for instance, `--follow` is the option one must provide to get `ripgrep` to use them in the way OP expects.

**Comment by dyng** [comment]
@ErichDonGubler Thanks for your information, it helps a lot.

**Comment by dyng** [comment]
@tubecube I have done this, please update to the latest version.
