### ISSUE TITLE
支持异步之后，在Windows上使用会有“Failed to stop Job” 这个错误。

### ISSUE THREAD

**Issue by Yggdroot** [dyng/ctrlsf.vim#243]
#### Issue description

支持异步之后，在Windows上使用，搜索某个单词，然后敲回车，会有“Failed to stop Job” 这个错误。

#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *Windows*        |
|   vim   | *gvim 8.0.1774* |

- log:

    ```vim
    " attach debug-mode log here
    " you can pipe logs into a file by vim's :redir command
    :let g:ctrlsf_debug_mode = 1
    :redir >/tmp/ctrlsf.log
    :CtrlSF something...
    :redir END
    ```
用上面方法得到的log内容：
```
Tokens: ['functools']
ParsedResult: {'pattern': 'functools'}
Options: {'pattern': 'functools', '_vimregex': '\V\cfunctools', '_vimhlregex': {'normal': '\V\c\(\^\d\+:\.\*\)\@<=functools', 'compact': '\V\c\(|\d\+ col \d\+|\.\*\)\@<=functools'}}
Tokens: ['-C', '3']
ParsedResult: {'context': 3}
ExecCommand: rg -C 3  --smart-case --fixed-strings --no-heading --color never --line-number -H -- "functools" "D:\\LeaderF"
TimerStarted: id=1
Searching...
HighlightRegex: \V\c\(\^\d\+:\.\*\)\@<=functools
处理 function ctrlsf#Search[15]..<SNR>54_ExecSearch[18]..<SNR>54_DoSearchAsync[4]..<SNR>54_Open[3]..ctrlsf#hl#HighlightMatch 时发生错误:
第   11 行:
E121: 未定义的变量: w:ctrlsf_match_hlid
处理 function ctrlsf#Search[15]..<SNR>54_ExecSearch[18]..<SNR>54_DoSearchAsync[4]..<SNR>54_Open[3]..ctrlsf#hl#HighlightMatch 时发生错误:
第   11 行:
E116: Invalid arguments for function matchdelete
DefactorizeLine: [Factor]: [D:\\LeaderF\autoload\leaderf\bufExpl.py, 5, import re], [Orig]: D:\\LeaderF\autoload\leaderf\bufExpl.py-5-import re
DefactorizeLine: [Factor]: [D:\\LeaderF\autoload\leaderf\bufExpl.py, 5, import re], [Orig]: D:\\LeaderF\autoload\leaderf\bufExpl.py-5-import re
StopTimer: id=1
Done!
ParseFinish

StopSearch
Failed to stop Job.
```

- vimrc:

无

**Comment by dyng** [comment]
不好意思，最近实在太忙，现在才有时间来处理 issue。

从代码上来看，应该是 `job_stop` 方法在 windows 上不支持通过 `term` 方式终止进程。

```vim
        if has('nvim')
            let stopped = jobstop(s:job_id)
        else
            let stopped = job_stop(s:job_id, "int")
        endif
        if stopped
            call s:DiscardResult()
            let s:cancelled = 1
            let s:done = 1
        else
            call ctrlsf#log#Error("Failed to stop Job.")
        endif
```

但因为我没有 windows 系统的机器，很难测试，不知你可否帮我测试一下，在 windows 系统上使用什么方式终止进程比较好？

**Comment by Yggdroot** [comment]
我对vim的job api没有研究，这个忙估计帮不上了。

**Comment by dyng** [comment]
@Yggdroot 嗯，好的。

想起来 @skywind3000 也使用的是 windows，有遇到这个问题吗？

**Comment by Yggdroot** [comment]
@wsdjeg 好像对job api挺有研究，不知道有没有空看看？

**Comment by wsdjeg** [comment]
@Yggdroot 我看了下 Vim8 的 job api 中 `job_stop` 函数的功能想对多一点，可以使用 `job_stop(id, 'kill')` 来停止，此外，这个函数的返回值仅仅是 stop 命令能否正确执行，并不是job是否stop的标志，可以使用 `job_status` 来检测。 在 neovim 中，job 并不是及时 stop 的，正常情况下会有一个 timeout 的时间。

**Comment by wsdjeg** [comment]
可以将 `if stopped` 该为 `if job_status(s:job_id) ==# 'dead'`

**Comment by dyng** [comment]
@wsdjeg 其实我只关心是否发出了 stop 命令，不必真的等待 job 终止，所以不需要使用`job_status`函数。是我的变量名起得不是太好。

现在的问题是不清楚为什么 `job_stop` 函数在 windows 上失败了。是所有的 windows 都有这个问题？还是 @Yggdroot 特有的？

**Comment by Yggdroot** [comment]
应该不是特有的，我的操作很一般化。

**Comment by Yggdroot** [comment]
@Yggdroot 我看了下 Vim8 的 job api 中 job_stop 函数的功能想对多一点，可以使用 job_stop(id, 'kill') 
    来停止，此外，这个函数的返回值仅仅是 stop 命令能否正确执行，并不是job是否stop的标志，可以使 
    用 job_status 来检测。 在 neovim 中，job 并不是及时 stop 的，正常情况下会有一个 timeout 的时 间。

@dyng 看了一下help，@wsdjeg 说的有道理。job_stop()只是返回 stop 命令能否正确执行。
```
                The result is a Number: 1 if the operation could be executed,
		0 if "how" is not supported on the system.
		Note that even when the operation was executed, whether the
		job was actually stopped needs to be checked with
		|job_status()|.
```
因为在我按回车的时候，rg已经搜索结束了，这时候再调用job_stop()来stop rg，所以就返回了0了，因为它在stop一个不存在的进程，这个操作是无效的。
所以正确的做法应该是用job_status()来判断是否结束。
而且， ` call ctrlsf#log#Error("Failed to stop Job.")` 感觉也没必要。
`

**Comment by dyng** [comment]
@Yggdroot 

> rg已经搜索结束了，这时候再调用job_stop()来stop rg，所以就返回了0了。

我在mac上，同样是rg已经搜索结束，调用`job_stop()`返回的是1。

不过我现在改成无论返回值多少，一律当做搜索已停止来处理。你试下`fix/failed-to-stop-job`这个分支看看。

**Comment by Yggdroot** [comment]
win上可能比较特殊。

试了一下fix/failed-to-stop-job，没问题了，可以merge过去了，thanks。
