### ISSUE TITLE
实时显示当前位置是搜索结果中的第几个

### ISSUE THREAD

**Issue by Brook3** [dyng/ctrlsf.vim#249]
* 希望搜索结果能够一直显示在第一行，而不是翻屏后就消失了。
* 还有，希望在搜索结果列表中查看时，能够显示现在查看的是第几处，第几个文件。我觉得这样观看更友好
```vim
50 matched lines across 20 files. Done! 
```

**Comment by dyng** [comment]
1. 目前很难实现。
2. 安装 airline 插件以后，可以显示当前文件名和当前位于第几个匹配处。

![image](https://user-images.githubusercontent.com/1492050/46570204-3288c600-c993-11e8-983c-c0ba3ed52099.png)
