### ISSUE TITLE
多级目录搜索，不能打开第二个结果

### ISSUE THREAD

**Issue by hw233** [dyng/ctrlsf.vim#256]
#### Issue description

*如果当前目录有多个文件夹，打开第一个结果正常，从第二个开始就找不到路径了，一直报下面这个错
Error detected while processing BufEnter Autocommands for "*":
E344: Can't find directory "dir2" in cdpath
E472: Command failed
我的目录结构:
test tree
.
├── dir1
│   └── a.py
└── dir2
│  └── b.py
*

#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *OS X Yosemite 10.12.1*        |
|   vim   | *VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 12 2018 10:54:33)* |
| backend |             *ack 2.24*              |
| locale  |            *en_US.UTF-8*             |

- log:

    ```vim
Tokens: ['hello']
ParsedResult: {'pattern': 'hello'}
Options: {'pattern': 'hello', '_vimregex': '\V\chello', '_vimhlregex': {'normal': '\V\c\(\^\d\+:\.\*\)\@<=hello', 'compact': '\V\c\(|\d\+ col \d\+|\.\*\)\@<=hello'}}
Tokens: ['-C', '3']
ParsedResult: {'context': 3}
ExecCommand: ag -C 3  --smart-case --literal --noheading --nogroup --nocolor --nobreak -- "hello" "/Users/zqb/test"
TimerStarted: id=3
Searching...
DefactorizeLine: [Factor]: [/Users/zqb/test/dir1/a.py, 2, #-*- coding:utf-8 -*-], [Orig]: /Users/zqb/test/dir1/a.py:2-#-*- coding:utf-8 -*-
    ```

- vimrc:

    ```vim
    let g:ctrlsf_position='right'
    nmap     <C-F>f <Plug>CtrlSFPrompt
    vmap     <C-F>f <Plug>CtrlSFVwordPath
    vmap     <C-F>F <Plug>CtrlSFVwordExec
    nmap     <C-F>n <Plug>CtrlSFCwordPath
    nmap     <C-F>N <Plug>CtrlSFCCwordPath
    nmap     <C-F>p <Plug>CtrlSFPwordPath
    let g:ctrlsf_auto_focus = {
                \ "at": "start"
                \ }

    map <F4> :CtrlSFOpen<cr>
    let g:ctrlsf_debug_mode = 1

    ```

- file:

    ```shell
    # please tell me something about files that CtrlSF doesn't work on.
    # if the content of file is private information, its encoding should be helpful.
    # it's important in some case!
    name: ctrlsf/plugin.vim
    encoding: utf-8
    content:
    # your file's content is here.
    ```

**Comment by dyng** [comment]
ctrlsf 没有使用`BufEnter`自动命令，可能是和其他插件冲突了，你先把其他插件禁用掉，然后再试一下？如果依然有报错，请把完整的日志信息贴一下。

**Comment by dyng** [comment]
你是不是用了自动切换工作目录的插件或者命令？所以打开dir1/a.py的时候切到dir1了

**Comment by hw233** [comment]
ctrlsf.vim
rainbow_parentheses.vim
vim-fugitive
vundle
我只剩下这四个插件了

**Comment by dyng** [comment]
你把所有 BufEnter 命令打印出来吧，看看有没有切换工作目录的自动命令

**Comment by hw233** [comment]
怎么打？没有用过这个BufEnter

**Comment by dyng** [comment]
:au BufEnter

你用的是某个vim发行版吗？（例如 SpaceVim），还是自己配置的 vimrc？

**Comment by hw233** [comment]
autocmd BufEnter * if bufname("") !~ "^\[A-Za-z0-9\]*://" | lcd %:p:h | endif
    au FileType gitcommit au! BufEnter COMMIT_EDITMSG call setpos('.', [0, 1, 1, 0])
可以了，我把配置文件里这两行给注释了就可以了，非常感谢，你这个插件真的是太好用了

**Comment by dyng** [comment]
哈哈，感谢使用 :)
