### ISSUE TITLE
[Feature] Ignore multiple directories

### ISSUE THREAD

**Issue by comatory** [dyng/ctrlsf.vim#266]
I can't figure out how to permanently ignore certain directories. I've tried option `-ignoredir "nameofdirectory"` which works fine for single directory but I don't know how to set it up for multiple directories.

**Comment by dyng** [comment]
Sorry for this late reply. Currently it's impossible to specify multiple directories using `-ignoredir`, but you can use `ctrlsf_ignore_dir` option instead.
