### ISSUE TITLE
Finding default root doesn't always work in a project, files don't open correctly from search results

### ISSUE THREAD

**Issue by synic** [dyng/ctrlsf.vim#267]
#### Issue description

finding default root doesn't always work in a project. 

When I search for a term, and click on a result, vim will open a new file instead of the file specified in the results. From what I can tell, it's because either the project root is wrong, or the relative path is not correct from the current context.

This doesn't always happen, sometimes results in the same search work, and some don't.

I have the following setting (though I used the default for a while, and added this setting to try and fix it without any luck): `let g:ctrlsf_default_root = 'project+wf`. 

The project is in a git repository without any submodules.

Here's a picture of what I mean. See how some of the paths are relative, some are absolute? Shouldn't they all be one or the other?

![Various paths](https://synic.world/s/e4dbb640.png)

#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *OS X Yosemite 10.10.5*        |
|   vim   | *MacVim 7.4 Included patches: 1-712* |
| backend |             *ag 0.31.0*              |
| locale  |            *en_US.UTF-8*             |

- log:

```vim
Tokens: ['TurnKey']
ParsedResult: {'pattern': 'TurnKey'}
Options: {'pattern': 'TurnKey', '_vimregex': '\V\CTurnKey', '_vimhlregex': {'normal': '\V\C\(\^\d\+:\.\*\)\@<=TurnKey', 'compact': '\V\C\(|\d\+ col \d\+|\.\*\)\@<=TurnKey'}}
ProjectRoot: 
ExecCommand: ag -C 3  --smart-case --literal -f --noheading --nogroup --nocolor --nobreak -- "TurnKey" "/private/tmp/ctrlsf.log"
TimerStarted: id=789
Searching...
HighlightRegex: \V\C\(|\d\+ col \d\+|\.\*\)\@<=TurnKey
6 fewer lines
StopTimer: id=789
Done!
ParseFinish
No matching autocommands
```

- vimrc:

```vim
let g:better_whitespace_filetypes_blacklist = ['ctrlsf']
let g:ctrlsf_default_view_mode = 'compact'
let g:ctrlsf_default_root = 'project+wf'
let g:ctrlsf_auto_close = {
            \ "normal": 0,
            \ "compact": 1
            \ }
let g:ctrlsf_auto_focus = {
            \ "at": "start"
            \ }
```

**Comment by dyng** [comment]
I'm sorry that I have missed this issue. Your log

```
ProjectRoot: 
```

shows that CtrlSF can't find a project root. CtrlSF first searches current file's directory for a VCS subdirectory (such as `.git`, `.svn`, `.bzr`), if not found, repeats searching in parent directory and so on.

I need more information about your project structure to know why ctrlsf can't find the root.

**Comment by synic** [comment]
There's a top level directory with a `.git`, and there are no other VCS directories in the project (we don't use submodules or anything like that).

It's a typical django structure something like the following:

```
toplevel
   \-- apps
         \-- calendars
         \-- blog
```

As far as I know, there are no other markers for the toplevel directory.  What other information can I give you?

**Comment by dyng** [comment]
@synic From the below line in your logs

```
ExecCommand: ag -C 3  --smart-case --literal -f --noheading --nogroup --nocolor --nobreak -- "TurnKey" "/private/tmp/ctrlsf.log"
```

I noticed that you invoked a searching against file `/private/tmp/ctrlsf.log`, no doubt ctrlsf couldn't find a project root because it searches project root from current file ant its parent directories.
