### ISSUE TITLE
Question: function declaration search

### ISSUE THREAD

**Issue by jbevarts** [dyng/ctrlsf.vim#268]
Thank you for your package; I enjoy it.

I'd like to search for a function declaration.  I don't want search results of all the times it appears in every file, just the declaration, either by explicitly typing it in or using the expression that's under the cursor.

Is this functionality included / possible?

**Comment by dyng** [comment]
It's impossible. The searching is implemented by underlying search backend(`rg`, `ag`, `ack`, etc.), I don't think they can search for declaration ONLY, by which means they must recognize syntax.
