### ISSUE TITLE
Write buffer corrupted when filename begins with number and dash

### ISSUE THREAD

**Issue by blay** [dyng/ctrlsf.vim#269]
#### Issue description

I search and open the edit window with filenames that begin with number and dash, such as:
201712180013-O-example.md

When editing even just a character and trying to save, I get "write buffer corrupted". The highlight of the files are also greyed out until [0-9]- similar to the line numbers of lines that does not have match:

201712180013-O-example.md
1-
2-
3: match
4- etc

If I change the filename to have space before dash, everything works as normal:
201712180013 -O-example.md

I assume it has to do with reading the edit buffer and getting confused when filenames look similar to how ctrlsf shows line numbers?

Have tried with several files, searches and edits, as well as both rg and ag as backend.

#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *Ubuntu 19.04*        |
|   vim   | *NVIM v0.3.7 |
| backend |             *ripgrep 0.10.0*              |
| locale  |            *en_US.UTF-8*             |

- log:
Tokens: ['-R', '-G', '*20*', '@todo:[b]']
ParsedResult: {'pattern': '@todo:[b]', 'regex': 1, 'filematch': 0}
Options: {'pattern': '@todo:[b]', 'regex': 1, 'filematch': 0, '_vimregex': '\v\c\@todo:[b]', '_vimhlregex': {'normal': '\v\c(^\d+:.*)@<=\@todo:[b]', 'compact': '\v\c(\|\d+ col \d+\|.*)@<=\@todo:[b]'}}
Tokens: ['-C', '3']
ParsedResult: {'context': 3}
ProjectRoot: /home/myuser/Dropbox/notes/md
ExecCommand: rg -C 3  --smart-case  --follow --no-heading --color never --line-number -H --no-hidden -- "@todo:[b]" "/home/myuser/Dropbox/notes/md"
TimerStarted: id=2
Searching...
HighlightRegex: \v\c(^\d+:.*)@<=\@todo:[b]
Error detected while processing function ctrlsf#Search[15]..<SNR>122_ExecSearch[18]..<SNR>122_DoSearchAsync[4]..<SNR>122_Open[3]..ctrlsf#hl#HighlightMatch:
line   11:
E121: Undefined variable: w:ctrlsf_match_hlid
Error detected while processing function ctrlsf#Search[15]..<SNR>122_ExecSearch[18]..<SNR>122_DoSearchAsync[4]..<SNR>122_Open[3]..ctrlsf#hl#HighlightMatch:
line   11:
E116: Invalid arguments for function matchdelete

[...Listing my filenames----]

ChannelClose
ConsumeResult: size=0
StopTimer: id=2
ElapsedTime: 1205
Done!
ParseFinish

-- INSERT --

CtrlSF's write buffer is corrupted. Note that you can't insert line/delete block/delete entire file in edit mode.

**Comment by blay** [comment]
Can confirm that removing the filename check as commented by @dyng in https://github.com/dyng/ctrlsf.vim/issues/78#issuecomment-151768808_ temporarily solves the issue.

**Comment by dyng** [comment]
Fixed in #270 , please checkout branch `fix/failed-to-save-files-starting-with-number` and have a try. Feel free to report any other bugs.
