### ISSUE TITLE
Way to determine project root (e.g. .git)?

### ISSUE THREAD

**Issue by collinpeters** [dyng/ctrlsf.vim#27]
Just wondering if there is a way to use ctrlsf in a git project folder? I have `autochdir` on as I like to use splits and NerdTree to navigate to other files. Also with CtrlP I am used it automatically searching the entire project.

**Comment by dyng** [comment]
Hi, @collinpeters 

Currently CtrlSF is just an interface of `ack` and `ag` (mainly for `ag`), it doesn't search project root itself but depends on the backend doing it (and `ag` do, by default).
It is possible for CtrlSF doing search like CtrlP, and it will improve user experience of ack-backed CtrlSF user. Thank you for your suggestion.

**Comment by collinpeters** [comment]
Can you link to some info on how ag does this? I haven't been able to find any info on it doing this.

**Comment by dyng** [comment]
I'm sorry for misleading you. `ag` works in cooperation with `git` that it respects `.gitignore`, but not "finding git root", I made a mistake here. I always set project root as my working directory myself, so I thought `ag` did it for me.

**Comment by dyng** [comment]
Add this feature in latest v1.0.

But it's turned off by default, you should enable it by `let g:ctrlsf_default_root = 'project'`.
