### ISSUE TITLE
how to change highlight color in result windows?

### ISSUE THREAD

**Issue by tillmanchen2015** [dyng/ctrlsf.vim#272]
It's not easy to see for my vim theme. Could you tell me how to modify it or add config?

**Comment by dyng** [comment]
By default ctrlsf using below highlighting configuration, you can override it in your vimrc.

```vim
" highlightment group can be shared between different syntaxes
hi def link ctrlsfFilename        Title
hi def link ctrlsfLnumMatch       SignColumn
hi def link ctrlsfLnumUnmatch     LineNr
hi def link ctrlsfSelectedLine    Visual
hi def link ctrlsfMatch           MatchParen
hi def link ctrlsfSearching       Todo
hi def link ctrlsfSearchDone      PreProc
hi def link ctrlsfSearchCancelled Comment
hi def link ctrlsfMatchCount      Number
hi def link ctrlsfFileCount       Number
hi def link qfFileName            Directory
hi def link qfError               Error
```

**Comment by soenkewindhausen** [comment]
Thank you for this great plugin. I use it every day. 
I am not a coder and spent a day trying to get the Titles of the results highlighted in Red. 

But It does not work. Would you help me? Thank you.

This is what I tried: 

`hi  ctrlsfFilename guifg=#fb4934 guibg=NONE guisp=NONE gui=bold ctermfg=30 ctermbg=NONE cterm=bold
`
`
hi! def link ctrlsfFilename Title
`

**Comment by dyng** [comment]
@soenkewindhausen Just drop this line in your `.vimrc`, 
```
hi ctrlsfFilename guifg=#ffffff guibg=NONE guisp=NONE gui=bold ctermfg=30 ctermbg=NONE cterm=bold
```
and `hi! def link ctrlsfFilename Title` is unnecessary.
