### ISSUE TITLE
Unclear documentation: g:ctrlsf_populate_qflist

### ISSUE THREAD

**Issue by smackesey** [dyng/ctrlsf.vim#274]
The docs say that `g:ctrlsf_populate_qflist`"Defines whether CtrlSF will feed quickfix and location list with search result."

This is confusing because the quickfix and location lists are different things. Does the plugin populate both? If it does, this behavior should be configurable (i.e. allow user to specify that only location OR quickfix list should be populated).

**Comment by dyng** [comment]
It's a mistake of docs. `g:ctrlsf_populate_qflist` only controls population of quickfix list but not location list, location list is ALWAYS populated.
