### ISSUE TITLE
Limit search to current file

### ISSUE THREAD

**Issue by blasco** [dyng/ctrlsf.vim#276]
First of all thank you for the outstanding plugin, I just love it. I use it to search and refactor within the project scope, but sometimes I would like to use it just for the current file, as the search output is so clear. Is it possible to limit a search to the current file?

**Comment by dyng** [comment]
Of cause you can. Try the following command:

```vim
:CtrlSF foobar %
```

**Comment by blasco** [comment]
Great! And could this by any chance done by a command so we don't need to add the `%` at the end? I'm not well versed in vimscript, but is there a way so I can do `:CtrlSFinFile search` so ti triggers `:CtrlSF search %`?

**Comment by dyng** [comment]
Using `%` in command line is a conventional way to specify current file, I think there is no need to add a new command. But if you would add it yourself, you can define it by commands below:

```vim
com! -n=1 CtrlSFinFile CtrlSF <q-args> %
```

**Comment by blasco** [comment]
Great, thank you
