### ISSUE TITLE
"Nothing found!" message is written to the wrong window when using compact mode

### ISSUE THREAD

**Issue by schfkt** [dyng/ctrlsf.vim#286]
If you try to find something using compact mode and there are no results found, the message "Nothing found!" will be written to the window you was focused on, instead of the ctrlsf's result window. For example:

<img width="1423" alt="Screenshot 2020-03-13 at 16 41 52" src="https://user-images.githubusercontent.com/3599143/76631662-b496fa00-654a-11ea-9dbd-5910efcec7c4.png">

#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *macOS Catalina 10.15.2*        |
|   vim   | *VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  3 2020 01:40:55) Included patches: 1-200* |
| backend |             *ag 2.2.0*              |
| locale  |            *en_US.UTF-8*             |

**Comment by dyng** [comment]
I have fixed it in the above pull-request. Please checkout the fix branch and have a try. Feel free to append any feedback.

**Comment by schfkt** [comment]
@dyng It works fine now. Thanks!

**Comment by dyng** [comment]
Merged. Thank you for your bug report!
