### ISSUE TITLE
怎么能无视我的gitignore？

### ISSUE THREAD

**Issue by ilaipi** [dyng/ctrlsf.vim#288]
我的目录结构：

- project
 - a-1
 - a-2
 - a-3
 - others..

因为一些原因，我这个仓库的gitignore里配置了   a-*

搜索的时候，就忽略了a-*下的任意文件

我可以通过`let g:ctrlsf_ignore_dir = ["node_modules", "package-lock.json", "yarn.lock"]`
来指定我需要忽略的文件，但并不希望我gitignore的文件也被忽略

**Comment by dyng** [comment]
根据`.gitignore`忽略文件是你的搜索后端的功能（rg, pt都有这个功能），你需要修改对应搜索后端的配置。

**Comment by ilaipi** [comment]
ctrlsf 在没有“搜索后端”的情况下能工作吗？
我看我的vim没有装rg  pt这样的插件了

（配置用的是k-vim）

**Comment by dyng** [comment]
@ilaipi ctrlsf 必须有搜索后端才能工作。ctrlsf 支持的后端包括：rg，ag，ack，pt，你可能已经装了其中的一个。

**Comment by ilaipi** [comment]
谢谢，是`ag`，我一直以为所谓的后端是另外一个插件，原来是系统里的一个程序。

看了ag的文档，大家一直讨论的增加.agrc配置文件的提议一直没有被合并到主仓库。。。

配置了alias  ag -u 竟然也达不到效果。。无奈
