### ISSUE TITLE
'wincmd w' throws a range error when preview window is open

### ISSUE THREAD

**Issue by dyng** [dyng/ctrlsf.vim#29]
``` vim
    if a:mode == 1 && g:ctrlsf_auto_close
        let ctrlsf_winnr = s:FindCtrlsfWindow()
        if ctrlsf_winnr <= target_winnr
            let target_winnr -= 1
        endif
        call s:CloseWindow()
    endif
```

The `target_winnr` is incorrect as preview window will be closed together with origin ctrlsf window. In this case, `let target_winnr -= 2` is correct.

**Comment by sandric** [comment]
yep, issuing the same

**Comment by sandric** [comment]
Is there any quick fix solution?

**Comment by sandric** [comment]
ok, as a quick fix I just stubbed `g:preview_window_opened` to 1 in `s:OpenPreviewWindow` and zeroing in `s:ClosePreviewWindow`
```vim 
if a:mode == 1 && g:ctrlsf_auto_close
        let ctrlsf_winnr = s:FindCtrlsfWindow()
        if ctrlsf_winnr <= target_winnr
            if g:preview_window_opened
              let target_winnr -= 2
            else
              let target_winnr -= 1
            endif
        endif
        call s:CloseWindow()
endif
```

**Comment by dyng** [comment]
@sandric Today I have released v1.0 and this issue is fixed there. Please update to the latest version, but be aware of that it breaks backward-compatibility.

**Comment by sandric** [comment]
oh, ok)

**Comment by dyng** [comment]
@sandric There are many changes in v1.0, please read the latest README first. If there is still bugs or you have any feature suggestion, feel free to open a new issue.

**Comment by sandric** [comment]
Yeah, I'm looking just now, edit mode is great actually. The thing is I'm kinda turn my vim into 'insert mode by default' emacs-style editor and have already tweaked it a bit for my mappings(
