### ISSUE TITLE
Doesn't do recursive searching in project?

### ISSUE THREAD

**Issue by NullVoxPopuli** [dyng/ctrlsf.vim#290]
## Before submitting your issue（请在提交 issue 前一定要检查以下项目！）

1. Update to the latest version of CtrlSF.
2. Update your backend(ag/ack/pt/rg) to their latest version.
3. Enable debug mode to try to find what is going wrong yourself. You can enable debug mode by `let g:ctrlsf_debug_mode = 1`.

If you can't find out why things do not work or can be sure it's a bug of CtrlSF, please fulfill below issue template. Thanks in advance!

#### Issue description

*You can describe your issue here.（请将你的 issue 内容填写于此）*

It seems the search with this minimal config does not search over files in directories.

```
# cwd is my dotfiles repo
$ nvim -u home/.config/nvim/-tests/ctrlsf.vim
```
```vim
call plug#begin('~/.local/share/nvim/plugged')

  Plug 'dyng/ctrlsf.vim'
  let g:ctrlsf_default_root = 'cwd'
  let g:ctrlsf_auto_focus = {
      \ 'at': 'start',
      \ }

call plug#end()

nmap <C-f> <Plug>CtrlSFPrompt
vmap <C-f> <Plug>CtrlSFVwordExec
```
#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *Ubuntu 19.10*        |
|   vim   | *NVIM v0.5.0-426-g30a6e374d* |
| backend |             *ag version 2.2.0*              |
| locale  |            *en_US.UTF-8*             |

- log:

    ```vim
    " attach debug-mode log here
    " you can pipe logs into a file by vim's :redir command
    :let g:ctrlsf_debug_mode = 1
    :redir >/tmp/ctrlsf.log
    :CtrlSF something...
    :redir END
    ```

```


StopJob
StopTimer: id=-1
Tokens: ['nmap']
ParsedResult: {'pattern': 'nmap'}
Options: {'pattern': 'nmap', '_vimregex': '\V\cnmap', '_vimhlregex': {'normal': '\V\c\(\^\d\+:\.\*\)\@<=nmap', 'compact': '\V\c\(|\d\+ col \d\+|\.\*\)\@<=nmap'}}
Tokens: ['-C', '3']
ParsedResult: {'context': 3}
ExecCommand: rg -C 3  --smart-case --fixed-strings --follow --no-heading --color never --line-number -H -- 'nmap' '/home/lprestonsegoiii/Development/NullVoxPopuli/dotfiles'
TimerStarted: id=1
Searching...
HighlightRegex: \V\c\(\^\d\+:\.\*\)\@<=nmap
ConsumeResult: size=0
ChannelClose
ConsumeResult: size=0
StopTimer: id=1
Done!
ParseFinish
```

I tried `ag nmap` in my terminal, and had similar results.

So, this is a problem with my silver searcher config, but I'm posting here for searchability.
Will post solution when I find it.

**Comment by NullVoxPopuli** [comment]
oh, it executed rip grep, interesting. (just read the log)

**Comment by NullVoxPopuli** [comment]
well, ripgrep appears to behave the same as ag -- no results. :-\

**Comment by NullVoxPopuli** [comment]
I wonder if it's annoying my folders that start with a `.`

**Comment by NullVoxPopuli** [comment]
the stuff I'm searching for is in a directory called `.config`

**Comment by NullVoxPopuli** [comment]
yup, that's it. if I cd into `.config`, I can find what I'm looking for (`nmap`). So... there must be a setting to change what stuff is ignored?

**Comment by NullVoxPopuli** [comment]
Maybe related to #188

**Comment by NullVoxPopuli** [comment]
oh! looks like this is it:
```
$ rg 'nmap'
# nothing
$ rg 'nmap' --hidden
.config/nvim/keymap.vim
26:nmap <leader>, :q<CR>
27:nmap <leader>. :qa<CR>
43:nmap <C-f> <Plug>CtrlSFPrompt
47:nmap <C-t> :Files<CR>
# ...
```
so that means, I need to set `g:ctrlsf_extra_backend_args`

**Comment by NullVoxPopuli** [comment]
solution:
```
  let g:ctrlsf_extra_backend_args = {
      \ 'rg': '--hidden',
      \ }
```

yay

**Comment by dyng** [comment]
Happy to hear that you figured it out :)
