### ISSUE TITLE
CtrlSF not working in NeoVim 0.5 branch

### ISSUE THREAD

**Issue by Nazeehe** [dyng/ctrlsf.vim#291]
I am on latest version as of 5/30/2020. Just ran PlugUpdate now and no updates.

OS: Windows 10
On NVIM v0.5.0-530-g618e9a769

What I am trying to do is search/replace across files. So I run :CtrlSF <keyword> and the search finds all instances of the word across my files. Great.

I then do a :<>s/word/replacement in the CtrlSF buffer and it changes all of them.
I do :w in the same buffer to save all files. CtrlSF asks me to confirm that 4 files will be changed. I pick Y for yes.
It then complaints that the files have been changed and I should do :CtrlSFUpdate to update my search results. 
Files are not saved with the changes. 

I attempted same flow with multip-cursors. Same thing.

Am I doing this wrong? I made sure that the keyword I am changing doesn't change one of the files names as I have run into that issue before. 

I am pretty sure I did this flow a few weeks before and it worked. Any thoughts?

**Comment by Nazeehe** [comment]
Hmm... ok... it works in Vim and in NeoVim 0.4. Looks like something broke it in NeoVim 0.5 pre-release branch.

**Comment by dyng** [comment]
Sorry for this late reply. You can enable the debug mode (`let g:ctrlsf_debug_mode = 1`) to see why CtrlSF complaints about the file has been changed, you can also paste the logs in this issue.

**Comment by Nazeehe** [comment]
Log when it does the %s/<foo>/<bar> replacement:

DefactorizeLine: [Factor]: [C:\Users\nazeehe\source\vim\dotfiles\plugins.vim, 32, augroup end^M], [Orig]: C:\Users\nazeehe\source\vim\dotfiles\plugins.vim-32-augroup end^M
ConsumeResult: size=0
ChannelClose
ConsumeResult: size=0
StopTimer: id=2
ParseFinish
1 change; before #3  2 seconds ago
4 substitutions on 4 lines
UnrenderedResultSet: [{'lnum': function('ctrlsf#class#paragraph#Lnum'), 'range': function('ctrlsf#class#paragraph#Range'), 'trim_tail': function('ctrlsf#class#paragraph#TrimTail'), 'vlnum': function('ctrlsf#class#paragraph#Vlnum'), 'setlnum': function('ctrlsf#class#paragraph#SetLnum'), 'matches': function('ctrlsf#class#paragraph#Matches'), 'lines': [{'lnum': 2, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': ''}, {'lnum': 3, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': 'ugroup DelayLoad_EasyClip^M'}, {'lnum': 4, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '   autocmd!^M'}, {'lnum': 5, 'match': {}, 'vlnum': -1,
'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '   autocmd ChangeMe * call plug#load(''vim-easyclip'') | autocmd! DelayLoad_EasyClip^M'}, {'lnum': 6, 'match':
{}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': 'ugroup end^M'}, {'lnum': 7, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '^M'}, {'lnum': 8, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '***************************^M'}], 'filename': 'dotfiles\easyclip.vim'}, {'lnum': function('ctrlsf#class#paragraph#Lnum'), 'range': function('ctrlsf#class#paragraph#Range'), 'trim_tail': function('ctrlsf#class#paragraph#TrimTail'), 'vlnum': function('ctrlsf#class#paragraph#Vlnum'), 'setlnum': function('ctrlsf#class#paragraph#SetLnum'), 'matches': function('ctrlsf#class#paragraph#Matches'), 'lines': [{'lnum': 2, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': ''}, {'lnum': 3, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': 'ugroup DelayLoad_IndenLines^M'}, {'lnum': 4, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '   autocmd!^M'}, {'lnum': 5, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '   autocmd ChangeMe * call plug#load(''indentLine'') | autocmd! DelayLoad_IndenLines^M'}, {'lnum': 6, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': 'ugroup end^M'}, {'lnum': 7, 'match':
{}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '***************************^M'}, {'lnum': 8, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '" Indent Lines^M'}], 'filename': 'dotfiles\indentlines.vim'}, {'lnum': function('ctrlsf#class#paragraph#Lnum'), 'range': function('ctrlsf#class#paragraph#Range'), 'trim_tail': function('ctrlsf#class#paragraph#TrimTail'), 'vlnum': function('ctrlsf#class#paragraph#Vlnum'), 'setlnum': function('ctrlsf#class#paragraph#SetLnum'), 'matches': function('ctrlsf#class#paragraph#Matches'), 'lines': [{'lnum': 2, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': ''}, {'lnum': 3, 'match': {}, 'vlnum':
-1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': 'ugroup DelayLoad_VisualMulti^M'}, {'lnum': 4, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '   autocmd!^M'}, {'lnum': 5, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '   autocmd ChangeMe * call plug#load(''vim-visual-multi'') | autocmd! DelayLoad_VisualMulti^M'}, {'lnum': 6, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': 'ugroup end^M'}, {'lnum': 7, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': ' let g:multi_cursor_use_default_mapping=0^M'}, {'lnum': 8, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': ''}], 'filename': 'dotfiles\multi_cursor.vim'}, {'lnum': function('ctrlsf#class#paragraph#Lnum'), 'range': function('ctrlsf#class#paragraph#Range'), 'trim_tail': function('ctrlsf#class#paragraph#TrimTail'), 'vlnum': function('ctrlsf#class#paragraph#Vlnum'), 'setlnum': function('ctrlsf#class#paragraph#SetLnum'), 'matches': function('ctrlsf#class#paragraph#Matches'), 'lines': [{'lnum': 28, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '^M'}, {'lnum': 29, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': 'augroup DelayLoad_Plugins^M'}, {'lnum': 30, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '    autocmd!^M'}, {'lnum': 31, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': '    autocmd ChangeMe * call plug#load(''targets.vim'', ''vim-sandwich'', ''vim-commentary'', ''vim-easymotion'', ''vim-CtrlXA'') | autocmd! DelayLoad_Plugins^M'}, {'lnum': 32, 'match': {}, 'vlnum': -1, 'setlnum': function('ctrlsf#class#line#SetLnum'), 'matched': function('ctrlsf#class#line#Matched'), 'content': 'augroup end^M'}], 'filename': 'dotfiles\plugins.vim'}]
ChangedFile: dotfiles\easyclip.vim
ChangedFile: dotfiles\indentlines.vim
ChangedFile: dotfiles\multi_cursor.vim
ChangedFile: dotfiles\plugins.vim
4 files will be saved. Confirm? (Y/n)



log when it fails to write:

InconsistentContent: [Lnum]: 2, [FileInMem]: ^M, [FileOnDisk]:
File dotfiles\easyclip.vim has been changed since last search. Skip this file. Please run :CtrlsfUpdate to update your search result.
InconsistentContent: [Lnum]: 2, [FileInMem]: ^M, [FileOnDisk]:
File dotfiles\indentlines.vim has been changed since last search. Skip this file. Please run :CtrlsfUpdate to update your search result.
InconsistentContent: [Lnum]: 2, [FileInMem]: ^M, [FileOnDisk]:
File dotfiles\multi_cursor.vim has been changed since last search. Skip this file. Please run :CtrlsfUpdate to update your search result.
InconsistentContent: [Lnum]: 28, [FileInMem]: ^M, [FileOnDisk]:
File dotfiles\plugins.vim has been changed since last search. Skip this file. Please run :CtrlsfUpdate to update your search result.
0 files are saved (4 skipped).

**Comment by dyng** [comment]
Looks like the `split()` function is broken in NeoVim 0.5 pre-release.

``` vim
    " in case of mixed text from win-style files and unix-style files, breaks
    " result into lines by both <CR><NL> and <NL>.
    let result_lines = split(a:result, '\v(\r\n)|\n')
```

should split result into lines without `^M`, but not so in your logs.

**Comment by dyng** [comment]
Close this issue. Feel free to reopen it if any updates.
