### ISSUE TITLE
Vertical split

### ISSUE THREAD

**Issue by timsofteng** [dyng/ctrlsf.vim#295]
Hello.

How I can to open found file in vertical split window? I mean real file editing, not just preview.

Thanks!

**Comment by dyng** [comment]
Vertical split is not assigned a key by default, you can turn on it by
```vim
let g:ctrlsf_mapping = {
    \ "vsplit": "o"
    \ }
```

**Comment by timsofteng** [comment]
@dyng sorry, but it doesn't work.

nmap <Leader>sf <Plug>CtrlSFPrompt
vmap <Leader>sf <Plug>CtrlSFVwordPath
let g:ctrlsf_auto_focus = {
    \ "at": "start"
    \ }
let g:ctrlsf_mapping = {
    \ "vsplit": "Enter"
    \ }

What did I do wrong?

**Comment by dyng** [comment]
You should use `<CR>` instead of `Enter`.

```vim
let g:ctrlsf_mapping = {
\ "vsplit": "<CR>"
\ }
```
