### ISSUE TITLE
在设置set encoding=utf-8后，中文名字乱码

### ISSUE THREAD

**Issue by iamcco** [dyng/ctrlsf.vim#30]
**.vimrc**配置
set encoding=utf-8
`:CtrlSF vim` 
搜索结果，中文**文件名**乱码
貌似还不能搜索中文

**Comment by dyng** [comment]
#12 可能和此issue重复。

提交bug时，请同时给出以下信息：

1. 系统版本
2. vim版本
3. ag(ack)版本
4. 相关配置项

关于无法搜索中文：
CtrlSF只是ag(ack)的界面，自身不具备搜索功能，请检查你安装ag(ack)是否可以正常搜索中文。

**Comment by iamcco** [comment]
还真是重复了，因为locale和设置编码不一样导致，和fugitive插件一样

**Comment by franckXu** [comment]
我直接用ag搜索中文无结果，需要如何设置吗？谢谢。

**Comment by dyng** [comment]
@franckXu 我在osx 10.11下测试，搜索中文没有问题。没有任何特别的设置。

最好确认：

1. shell的locale设定。
2. 文件的编码。
3. （如果是使用ctrlsf的话）vim的编码。

以上编码是否相同。

**Comment by franckXu** [comment]
js文件的编码从utf-8改为ansi就可以了。
如果都改为ansi的话，都不会引起别的问题?文件编码不是很了解。
