### ISSUE TITLE
Question: about a hack in the source code

### ISSUE THREAD

**Issue by zzxoto** [dyng/ctrlsf.vim#300]
Have you guys any insight into how this hack solves the problem of g:CtrlSFGetVisualSelection(); because I stumbled into this problem that visual selection was "stale" when just plainly using that function

P.S. I posted this question mistakenly at [vim plug](https://github.com/junegunn/vim-plug/issues/1029) repository instead initally.

**Comment by dyng** [comment]
I'm sorry that the hacky code is written in 6 years ago so I can't recall anything about how it works. Sorry I can't help you much.
