### ISSUE TITLE
Error in ctrlsf#fs#FindProjectRoot

### ISSUE THREAD

**Issue by lervag** [dyng/ctrlsf.vim#307]
https://github.com/dyng/ctrlsf.vim/blob/1afb4e2117026a27a2960f68ef96fc99597526ad/autoload/ctrlsf/fs.vim#L20-L26

The `marker` variable is not always available. This means the second conditional is an error if `g:ctrlsf_extra_root_markers <= 0`.

**Comment by dyng** [comment]
Oops, a naive mistake.

**Comment by dyng** [comment]
@lervag Thanks for your quick feedback about this bug!

**Comment by lervag** [comment]
No probem, happy to be of help :)

**Comment by lervag** [comment]
And thanks for the quick fix!
