### ISSUE TITLE
Keymap to open file in a vertical split

### ISSUE THREAD

**Issue by ssoulless** [dyng/ctrlsf.vim#309]
To open file in horizontal split window you can use `<C-O>`. I cannot find the way of opening file in a vertical split. There should be a default keymap for this.

**Comment by dyng** [comment]
`ctrlsf.vim` has `vsplit` is what you need but it is not assigned a key by default. You can do it yourself:
```vim
let g:ctrlsf_mapping = {"vsplit": "<your_key>"}
```

**Comment by ssoulless** [comment]
Why not add the keymap by default?
