### ISSUE TITLE
是否可以提供在右侧窗口水平分屏打开的功能

### ISSUE THREAD

**Issue by wklken** [dyng/ctrlsf.vim#31]
重构代码时经常用到
单屏 -> 调用搜索 -> 在左侧窗口, 此时跳到左侧窗口, 选中一个, 更希望的是原先右侧窗口不动, 在其上方水平分屏打开选中位置所在文件, 修改完毕后退出 又回到搜索的左侧分屏, 便于快速重构代码

目前使用tab, 需要不停切换

感谢, 插件很强大:)

**Comment by dyng** [comment]
![](http://i.imgur.com/yc3SABT.png)

不知道我有没有理解错，是指上图这种形式吗？实现这个功能不是很困难，而且感觉可以在现有的 preview 窗口里面增加这个功能。

不过我推荐另一个插件 [gabesoft/vim-ags](https://github.com/gabesoft/vim-ags) ，edit mode 很好用，我在考虑能否 port 过来。

**Comment by wklken** [comment]
这就是我想要的

在左侧窗口, 选一行, qiuckfix改完, 切回左侧, 选另一行, 再修改, 重构时比较高效.
现在每次打开, 主窗口都没了.....有时候要找回来

期待新功能, thx

PS: 已在[k-vim](https://github.com/wklken/k-vim) version9.0 中加入ctrlsf.vim作为主要搜索插件

**Comment by dyng** [comment]
非常感谢 :)

ctrlsf 还有很多不太完善的地方，出现问题的时候请提 issue，我会尽快处理。

**Comment by dyng** [comment]
@wklken 已把v1.0分支merge到master了，增加了edit mode功能，不知能否满足你重构的需要？如果有什么问题或者建议，还请提出 :)

**Comment by wklken** [comment]
@dyng 已更新到最新, 试用了下, 对重构效率上提升很多, thx:)

反馈一个问题:
```
Bundle 'terryma/vim-multiple-cursors'
let g:multi_cursor_use_default_mapping=0
" Default mapping
let g:multi_cursor_next_key='<C-m>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'
```


我的multiple-cursors配置自定义`<ctrl-m>`, edit mode有问题, 如果是默认`ctrl-n`或者自定义改`ctrl-b`等都正常.

ctrl-m, 会自动跳转右侧窗口, 打开对应文件, 类似敲enter的效果

似乎原生vim, ctrl+m = enter? 排查中

**Comment by wklken** [comment]
已定位
```
<CR>            carriage return         CTRL-M   13     carriage-return
```

在一般窗口中 multiple-cursor 的keymapping有效, 在 ctrlsf 的窗口中, 似乎优先 => enter
我寻找下解决方法

再次感谢

**Comment by dyng** [comment]
应该是multiple-cursor在map了<CR>之后，被ctrlsf的map给覆盖掉了。

可以修改ctrlsf的默认map解决：

```vim
let g:ctrlsf_mapping = {
    \ 'open': 'o',
    \ }
```
