### ISSUE TITLE
How to specify search path?

### ISSUE THREAD

**Issue by ssoulless** [dyng/ctrlsf.vim#313]
I know you can specify `cwd` or `project` as deafult search path in configs, but cannot find the way to specify the search path in `:CtrlSF` command.

**Comment by dyng** [comment]
You can specify search path as the third argument of command `:CtrlSF pattern search_path`.

**Comment by ssoulless** [comment]
@dyng could you please provide an example? because it does not work for me

**Comment by dyng** [comment]
@ssoulless A trivial example is `:CtrlSF test /tmp` that will search `test` inside `/tmp` folder. If you still get in trouble, please toggle debug flag (`let g:ctrlsf_debug_mode = 1`) and paste debug log here.
