### ISSUE TITLE
*.hpp can't be find as default

### ISSUE THREAD

**Issue by Githubwyb** [dyng/ctrlsf.vim#314]
I use default config with ctrlsf.vim, but when I use `:CtrlSF xxx` to search, the hpp files not in the results.
`:CtrlSF -G **/*.* xxx` show the same result.
`:CtrlSF -G **/*.hpp xxx` show 0 files.

But when I use `:CtrlSF xxx **/*.*`, it has hpp files.

Every ctrlsf config is default.

**Comment by Githubwyb** [comment]
ack command doesn't have this problem.

**Comment by dyng** [comment]
The expression used in `-G` depends on your backend. While `rg` and `ack` accept glob as their input, `ag` and `pt` accept regular expression.
