### ISSUE TITLE
Is it possible to search sentences rather than just a single word?

### ISSUE THREAD

**Issue by hlf20010508** [dyng/ctrlsf.vim#333]
I don't know if i've missed anything in doc, but I didn't see any description about searching for a sentence.
Will you support it? Or you've already support?
Please let me know, thank you.

**Comment by dyng** [comment]
By "sentence" do you mean "a string contains whitespaces"? If so, please wrap you sentence with single quote.

**Comment by hlf20010508** [comment]
> By "sentence" do you mean "a string contains whitespaces"? If so, please wrap you sentence with single quote.

Yes. Thank you, it works. `’ ’`, `” ”`, `’’’ ’’’` they all work.
