### ISSUE TITLE
ctrlsf_backend keeps miserror

### ISSUE THREAD

**Issue by liweiwei111** [dyng/ctrlsf.vim#337]
vim8.2
let g:ctrlsf_backend = 'auto'
Can not locate auto in PATH, make sure you have it installed.

**Comment by McEazy2700** [comment]
I think my issue is similar. First I got
`g.ctrlsf_backend not defined or empty`
then I set it to auto but now I'm getting 
`Can not locate auto in PATH, make sure you have it installed`

**Comment by liweiwei111** [comment]
> I think my issue is similar. First I got `g.ctrlsf_backend not defined or empty` then I set it to auto but now I'm getting `Can not locate auto in PATH, make sure you have it installed`

哈哈

**Comment by dyng** [comment]
@liweiwei111 @McEazy2700 You should leave `g:ctrlsf_backend` undefined and ctrlsf will detect the backend. (make sure you have `rg`, `ag`, `pt` or `ack` installed)

The `let g:ctrlsf_backend = 'auto'` is a deprecated option and deleted a long time ago, but user manual is not updated correctly. (It's a mistake)
