### ISSUE TITLE
How can I replace all occurence of the searched keyword?

### ISSUE THREAD

**Issue by PezCoder** [dyng/ctrlsf.vim#339]
#### Issue description

I read through the docs, but unsure how can I replace occurrences of the keyword that is searched through ctrlsf.vim

#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *OS X Ventura 13.4 (22F66)*        |
|   vim   | *NVIM v0.7.0* |
| backend |             *ripgrep 13.0.0*              |
| locale  |            *?*             |

- vimrc:

    ```vim
    " dyng/ctrlsf.vim --- {{{
    " Defaults:
    " Case sensitive - smart
    " Regex - Literals by default. Use '-R' to pass regex
    let g:ctrlsf_default_view_mode = 'compact' " Quickfix like view
    let g:ctrlsf_populate_qflist = 1
    let g:ctrlsf_auto_close = {
        \ "compact": 0
        \}
    let g:ctrlsf_mapping = {
        \ "next": "n",
        \ "prev": "N",
        \ }
    let g:ctrlsf_auto_focus = {
        \ "at": "start"
        \ }
    nnoremap <Leader>/ :CtrlSF<Space>
    " }}}


    ```

- file:

    ```shell
    name: ctrlsf/plugin.vim
    encoding: utf-8
    content:
    Some occurrence of a word, & let's say there are multiple files, I want to replace occurrences of the found word how can I achieve this.
    ```

**Comment by dyng** [comment]
By 'replace occurrences of the found word' did you mean the edit mode? It allows you to perform a global replacement.

**Comment by PezCoder** [comment]
<img width="797" alt="Screenshot 2023-06-17 at 1 01 57 PM" src="https://github.com/dyng/ctrlsf.vim/assets/8057916/624d9403-3db6-4bb4-ac9f-df97484e6280">

Yes, that's correct. But I'm not able to make any replacements.
It seems like that's because I'm using the following line:
```
let g:ctrlsf_default_view_mode = 'compact' " Quickfix like view
```
If I comment on this, the replacements work. Is there any way I can make it work with the compact view?

**Comment by PezCoder** [comment]
I've realised that If I'm using quickfix list I can rather do the following to do search replacement:
```
:cdo %s/<search term>/<replace term>/cg
```
