### ISSUE TITLE
CtrlSFVwordPath and CtrlSFVwordExec mappings are not working

### ISSUE THREAD

**Issue by zaferot** [dyng/ctrlsf.vim#34]
Hi!
I am trying to get along with this useful plugin. But I cannot get working CtrlSFVwordPath and CtrlSFVwordExec mappings. I use key mappings from the doc. Also, I tried to play with them. But it does not help. I always get the following output and nothing happens:
`:call feedkeys(":\<C-U>CtrlSF " . g:CtrlSFGetVisualSelection()."\r")`

Can you please help me with this?

**Comment by dyng** [comment]
>  I always get the following output and nothing happens:
> :call feedkeys(":\<C-U>CtrlSF " . g:CtrlSFGetVisualSelection()."\r")

I'm not sure what you mean by "get the following output", can you attach a snapshot to explain it ?

And here is extra information I need to know

- OS version
- Vim version
- Your vimrc

**Comment by zaferot** [comment]
* OS: Arch Linux
* Vim version:
`VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 23 2015 11:26:12)
Included patches: 1-712
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -lruby -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib`

* My [`.vimrc`](https://github.com/zaferot/dotfiles/blob/master/.vimrc)
 
STR:
* Visually select a word;
* Press the key mapping  `<C-F>f`;

Right after that Vim is switched to `NORMAL` mode with the output like on the screenshot below and nothing happens.

I've just disabled all other plugins and the issue is still reproducible. 

![snapshot2](https://cloud.githubusercontent.com/assets/4263125/7553923/fd5da5c2-f718-11e4-9b4c-24714daab0cf.png)

**Comment by dyng** [comment]
If everything is right, there should be a `<CR>` follows `:call feedkeys(...)` and get the command executed, but it seems like that doesn't work like expected and I don't know why...

Can you test if following command works right?

```vim
nnoremap <expr> T ":echo('foo')\r"
```

**Comment by dyng** [comment]
There is another possibility that `:call feedkeys(...)` is executed but something goes wrong.

Can you tell me
1. If searching word under cursor (builtin map is `<Plug>CtrlSFCwordPath`) works well?
2. If `:call feedkeys(":echo('foo')\r")` works well?

Thank you.

**Comment by zaferot** [comment]
I've found the reason for this issue. It's due to my key mappings:
`nnoremap : ;`
 `vnoremap : ;`
 `nnoremap ; :`
 `vnoremap ; :`

I've disabled them. Sadly, these are quite handy.
Is it possible to somehow workaround this?

Thanks!

**Comment by dyng** [comment]
Fix it is not so hard, thanks for finding out the real reason :)

A fixed version have been merged, please update to the latest version. If the issue remains, comment here to let me know.

**Comment by zaferot** [comment]
It's working fine now!
Thanks!
