### ISSUE TITLE
Sync CtrlSF compact window when navigating via quickfix

### ISSUE THREAD

**Issue by PezCoder** [dyng/ctrlsf.vim#340]
#### A thank you note ❤️ 

First off, I want to thank you immensely for making this plugin! I think it works superbly out of the box, which is rarely the case with the plugins within VIM community.

I've had a terrible experience with other searches like rg, ack & their integration with VIM - as it required a lot of tweaks for basic features that modern IDEs provide.

#### Issue description

I'm using compact view with the setting to enable populating the quickfix list.
Since I've primarily migrated from using vim-ack which pretty much uses quickfix list extensively & opens that after search completion which stays in sync with where the user is in the quickfix list.

With CtrlSF, with the settings mentioned, you may search for a keyword & it populates 10 results, even if you keep navigating the quickfix using `:cnext` to 7th word, it doesn't updates the position of the cursor within CTRLSF search results window.

The expectation is for it to behave like quickfix window (if possible), or if there is a way for me to rather trigger `:copen` at the end of search instead of CTRLSF's window, that would also be great. The only caveat is, I wouldn't be able to leverage edit mode if I use quick fix list.

Here is a video of how quickfix list work:
https://asciinema.org/a/XWEijrJrtNhZGiSvmJUj7RKy5

Here is a video of how CtrlSF window works with the provided settings:
https://asciinema.org/a/KE39Zrf06KBo2Dpa4UxoAzyyh

#### Things about your system and environment（请在此填写你的系统信息）

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *OS X Ventura 13.4 (22F66)*        |
|   vim   | *NVIM v0.7.0* |
| backend |             *ripgrep 13.0.0*              |
| locale  |            *?*             |

- vimrc:

    ```vim
    " dyng/ctrlsf.vim --- {{{
    " Defaults:
    " Case sensitive - smart
    " Regex - Literals by default. Use '-R' to pass regex
    let g:ctrlsf_default_view_mode = 'compact' " Quickfix like view
    let g:ctrlsf_populate_qflist = 1
    let g:ctrlsf_auto_close = {
        \ "compact": 0
        \}
    let g:ctrlsf_mapping = {
        \ "next": "n",
        \ "prev": "N",
        \ }
    let g:ctrlsf_auto_focus = {
        \ "at": "start"
        \ }
    nnoremap <Leader>/ :CtrlSF<Space>
    " }}}


    ```

**Comment by dyng** [comment]
Sorry for this late reply, and thank you for your appreciation!

Compact mode is an interface that looks like quickfix but does not share same behaviors, if you prefer real quickfix window, a quick & dirty solution is using `g:CtrlSFAfterMainWindowInit` hook.

```vim
function! g:CtrlSFAfterMainWindowInit()
    close
    copen
endfunction
```

Compact mode is a design choice when I didn't fully understand quickfix window. As there are many plugins which enhance quickfix window recently, maybe I'll deprecate the compact mode later.

**Comment by PezCoder** [comment]
Thank you for the help! @dyng - This works great ❤️ 

I'm assuming there wouldn't be a way to get the best of both worlds is it? - I mean having a way to rename things (edit mode) + quick fix list together.

**Comment by PezCoder** [comment]
I think let me close this issue, I had created a separate issue asking that here: https://github.com/dyng/ctrlsf.vim/issues/339

**Comment by PezCoder** [comment]
Just want to let you know that, the above suggested solution to provide CtrlSFAfterMainWindowInit has some edgecase, especially when doing repeat searches.

Removing that function & using the following configuration rather worked for me seamlessly:

```
let g:ctrlsf_populate_qflist = 1
let g:ctrlsf_auto_close = 1
let g:ctrlsf_auto_qf = 1
```
