### ISSUE TITLE
Open file in vertical split?

### ISSUE THREAD

**Issue by sandric** [dyng/ctrlsf.vim#36]
Is there a way to open file from ctrlsf search results window not in tab, but in vertical split? thx.

**Comment by dyng** [comment]
It's a feature on my todo list after v1.0 release.  Currently you can open file only in previous window (if unmodified) or horizontal splitted window (if modified).

**Comment by dyng** [comment]
This feature is not as useful as before when edit mode had not been introduced, but to implement it will need a shortcut key in normal mode which is so valuable now. I'll consider about this feature if the needs really exist, but now I close this issue first.

**Comment by amree** [comment]
Hi. Just checking, this is still not possible, right?

**Comment by dyng** [comment]
Vertical split is already supported, but the trigger key is not mapped by default, you should map your own key for it. Please check out the [manual](https://github.com/dyng/ctrlsf.vim/blob/master/doc/ctrlsf.txt#L514).

**Comment by amree** [comment]
Awesome and I should've checked the manual as well just now for this information. Thanks @dyng
