### ISSUE TITLE
mapping not working

### ISSUE THREAD

**Issue by wyyqyl** [dyng/ctrlsf.vim#40]
None of those key mapping works for me.
for example: `nmap <C-F>f <Plug>CtrlSFPrompt`
After pressing Ctrl-F f, but nothing happened, so weird.
The plugin can work by manually inputting ':CtrlSF xxx'

Env: Ubuntu 14.04  VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:59) Included patches: 1-52

**Comment by dyng** [comment]
There are several reasons can break mapping.

1. check if key is mapped properly by `:nmap <C-F>f`.
2. maps conflict so often. disable plugins except ctrlsf.vim to see if this issue remains.
3. for maps including `<Plug>`, do not map it by `nnoremap`.
4. make sure your input is passed completely to vim but not something else like tmux.

**Comment by wyyqyl** [comment]
Thanks for the detailed explanation, I used `nnoremap` for mapping, it's my fault.
