### ISSUE TITLE
wrap around with <C-j> and <C-k>

### ISSUE THREAD

**Issue by cvlmtg** [dyng/ctrlsf.vim#42]
would it be possible to change, e.g., <C-j> to go back to the first match the the last is reached?

**Comment by dyng** [comment]
I have implemented this feature in `v1.1` branch, but need some time to test.

If you want a early taste, you can checkout `v1.1` in your local repository.

**Comment by cvlmtg** [comment]
thanks! :)

**Comment by dyng** [comment]
Implemented in 406572f.
