### ISSUE TITLE
honoring "set hidden"

### ISSUE THREAD

**Issue by cvlmtg** [dyng/ctrlsf.vim#45]
let's say I have a file open. I invoke ctrlfs and open another file from the results. if the previous file is saved, the buffer is replaced with the new file. if it is not saved, the buffer is split and the selected file is displayed above the unsaved one.

this could be fine when vim is configured with "set nohidden", but when "set hidden" is set I find this behavior a bit annoying. could you please modify the plugin to always replace the buffer when "hidden" is set?

thanks!

**Comment by dyng** [comment]
Fixed in #47 . Thank you for your bug report.

**Comment by cvlmtg** [comment]
thanks for your support :)
