### ISSUE TITLE
和 multiple cursor 冲突

### ISSUE THREAD

**Issue by yakiang** [dyng/ctrlsf.vim#51]
function! Multiple_cursors_before()
        if exists(':NeoCompleteLock')==2
            exe 'NeoCompleteLock'
        endif
    endfunction

    function! Multiple_cursors_after()
        if exists(':NeoCompleteUnlock')==2
            exe 'NeoCompleteUnlock'
        endif
    endfunction

为了使 multiple cursor 和 neocomplete 共存，我定义了上面两个函数（也是 multiple cursor 推荐的），然而这样做的结果是 ctrlsf 的快捷键都失效了，比如 `p`, `<cr>` 都无法打开。去掉正常。

**Comment by dyng** [comment]
抱歉，因为最近比较忙，我需要一些时间来重现这个bug。

已加入todo list。

**Comment by dyng** [comment]
安装了neocomplete和multiple-cursor的最新版后，无法重现这个bug。

希望能够提供以下信息：

1. （最重要）CtrlSF窗口中的map，可以用以下命令查看

    ```vim
    :nmap <buffer> p
    :nmap <buffer> <CR>
    ```
2. os, vim信息，相关插件的版本信息（commit sha1）
3. 在关闭除CtrlSF，neocomplete和multiple-cursor之外的plugin之后，是否依然能够重现bug
4. 具体的重现步骤

**Comment by yakiang** [comment]
忽然 ok 了，我也无法重现，抱歉耽误双方时间。

**Comment by dyng** [comment]
never mind :)
