### ISSUE TITLE
Results opening in a horizontal split

### ISSUE THREAD

**Issue by daveyarwood** [dyng/ctrlsf.vim#52]
Hi,

I'm not sure if this is a bug or a feature, but when I press `<CR>` to go to a file from CtrlSF results, it opens the file in a new horizontal split. I can't seem to find any option to customize this behavior. Is there a way to open the file without splitting?

**Comment by dyng** [comment]
I have not documented this (sorry for that) but designed behavior in opening file should be like:

if `hidden` is not set:

1. Try to open file in window where you launch CtrlSF, as long as buffer in that is not modified.
2. If not, split a horizontal window and open file.

if `hidden` is set:

1. Always open file in window where you launch CtrlSF.

If CtrlSF does not work in way I described, it may be a bug. Please report here and I'll take a look at it. Thanks in advance.

P.S. Currently there is no option for controlling this behavior (except `hidden`), I'm thinking to add a command by which user can order to split explicitly.

**Comment by daveyarwood** [comment]
Hmm... I am seeing the first behavior (try to open the file in the window where you launch CtrlSF, unless there are unsaved changes, in which case, do a horizontal split), regardless of whether `hidden` is set.

**Comment by dyng** [comment]
This is a feature requested in #45 , and I agreed on that is more natural for whom has set `hidden`.

In next version user can explicitly split window, no matter `hidden` is set or there exists unsaved changes, I'll leave this issue open until then.

**Comment by daveyarwood** [comment]
OK, sounds good.

Thanks for such a great plugin! I use it all the time. :)

**Comment by dyng** [comment]
Thank you. If you find it helps then you can star it :)

I have implement this feature in `v1.2`, you can have a early taste if you checkout that branch in your local repository.

**Comment by daveyarwood** [comment]
I checked out the v1.2 branch, and it solves this issue :+1:

**Comment by dyng** [comment]
Glad to hear that :)

**Comment by dyng** [comment]
merged in #59 .
