### ISSUE TITLE
:w ERROR

### ISSUE THREAD

**Issue by airhuman** [dyng/ctrlsf.vim#53]
Error detected while processing function ctrlsf#Save..ctrlsf#edit#Save..<SNR>144_Diff..<SNR>144_DiffFile:
line    3:
E605: Exception not caught: InconsistentException
Error detected while processing function ctrlsf#Save..ctrlsf#edit#Save..<SNR>144_Diff:
line   12:
E171: Missing :endif

ctrlsf.vim version:
➜  ctrlsf.vim git:(master) ✗ git branch -av
* master                3a99228 Merge pull request #50 from dyng/hotfix/restoring-fixed-window-size

**Comment by airhuman** [comment]
Error detected while processing function ctrlsf#Save..ctrlsf#edit#Save..<SNR>140_SaveFile..<SNR>140_VerifyConsistent:
line    6:
E684: list index out of range: 2
E15: Invalid expression: line.content !=# a:buffer[ln-1]
Error detected while processing function ctrlsf#Save..ctrlsf#edit#Save..<SNR>140_SaveFile..<SNR>140_WriteParagraph:
line   34:
E684: list index out of range: 2
Error detected while processing function ctrlsf#Save..ctrlsf#edit#Save..<SNR>140_SaveFile..<SNR>140_VerifyConsistent:
line    6:
E684: list index out of range: 2
E15: Invalid expression: line.content !=# a:buffer[ln-1]
Error detected while processing function ctrlsf#Save..ctrlsf#edit#Save..<SNR>140_SaveFile..<SNR>140_WriteParagraph:
line   34:
E684: list index out of range: 2

**Comment by dyng** [comment]
Thank you for bug report. `InconsistentException` is thrown by design but I forget to catch it.

I'll fix it soon.

**Comment by dyng** [comment]
Fixed in #54.

If you found this issue is not fixed or any other problem, please reopen or create a new issue. Thanks!
