### ISSUE TITLE
E684: list index out of range: 2 Error detected while processing function ctrlsf#Save..ctrlsf#edit#Save..<SNR>140_SaveFile..<SNR>140 _VerifyConsistent

### ISSUE THREAD

**Issue by airhuman** [dyng/ctrlsf.vim#55]
在使用中，发现如下ERROR

![image](https://cloud.githubusercontent.com/assets/1021047/8936061/b632771a-3582-11e5-90df-099d1bab9970.png)

![image](https://cloud.githubusercontent.com/assets/1021047/8936079/d28b431a-3582-11e5-9155-61ada2da7747.png)

然后Ctrl-j跳转第一个welcome上，再使用multicursor，将三个文件中的welcome更新到Welcome
再保存 :w 

![image](https://cloud.githubusercontent.com/assets/1021047/8936119/10e10dca-3583-11e5-8c77-5065bcece203.png)

![image](https://cloud.githubusercontent.com/assets/1021047/8936124/16cf2e06-3583-11e5-81ec-126cdef20465.png)

![image](https://cloud.githubusercontent.com/assets/1021047/8936138/25aa3704-3583-11e5-9737-97d6466f91bf.png)

![image](https://cloud.githubusercontent.com/assets/1021047/8936144/2fa3e160-3583-11e5-9f62-b0d8ac57e7de.png)

![image](https://cloud.githubusercontent.com/assets/1021047/8936152/3b2db75e-3583-11e5-952f-2cb0317e59a9.png)

![image](https://cloud.githubusercontent.com/assets/1021047/8936157/47b1704c-3583-11e5-8a68-7ed87eebe538.png)

文件更新是成功的，就出现如下ERROR了，可以避免吗？

**Comment by dyng** [comment]
这是一个已知的ag的bug。

问题出在如果文件行尾有LF时，ag输出的结果会包含一个空行（在你的例子中，`a.txt`只有2行，但是ag的结果却有3行），所以导致写入时超出了buffer的长度。

https://github.com/ggreer/the_silver_searcher/issues/685

我已经向ag项目报告了这个bug，不过目前还未得到处理。

一个临时的解决办法是换用ack，ack在我测试的版本中没有这个bug。
根本的解决办法自然是ag解决这个bug，不过如果实在得不到解决就只能在ctrlsf里面work around掉。

**Comment by airhuman** [comment]
多谢及时回复，我先小忍下吧

**Comment by dyng** [comment]
Close in favor of #64
