### ISSUE TITLE
Incorrect complain about file has been changed since last search

### ISSUE THREAD

**Issue by tex** [dyng/ctrlsf.vim#58]
Hi, this is a great plugin, but this error makes it not very usefull.

It is inside a git repository and I know for sure that file has not been modified since last search. Also running CtrlsfUpdate doesn't help since it shows exactly the same result and also editing and writing fails with the same error.

File ... has been changed since last search. Skip this file. Please run :CtrlsfUpdate to update your search result.
d since last search. Skip this file. Please run :CtrlsfUpdate to update your search result.
0 files are saved (1 skipped).

**Comment by dyng** [comment]
There is several reasons can mess up CtrlSF's saving. I need more information to debug.

Please update to latest version, and turn on debug mode by `let g:ctrlsf_debug_mode = 1`.

Keep an eye on error message of `InconsistentContent`, which contains hints about which line has been changed, content of that line in memory and on disk. Please check what's wrong with them.

If you can't figure out what is going wrong, report here. And also with your system's information, like

* os
* vim's version
* backend (ag or ack?), its version

**Comment by tex** [comment]
I found the reason. It is about different line endings. That ^M thing when Windows file is opened in Linux... Not sure how to fix it... Do you think it is a good idea to add option to ignore whitespace changes in InconsistenContent check?

**Comment by dyng** [comment]
Thank you for your helpful bug report, I have fixed this bug in #59 .

It will be soon merged into `master` as `v1.2`.

**Comment by dyng** [comment]
The fix has been merged into `master`.

I'll close this issue. But if you find the fix has not actually fixed, feel free to reopen this.

**Comment by tex** [comment]
I tried it on rather large number of files:

Chyba při zpracování function ctrlsf#Save..ctrlsf#edit#Save..<SNR>156_SaveFile..<SNR>156_VerifyConsistent:
řádek    6:
E684: list index out of range: 84
E15: Chybný výraz: line.content !=# a:on_disk[ln-1]
Chyba při zpracování function ctrlsf#Save..ctrlsf#edit#Save..<SNR>156_SaveFile..<SNR>156_WriteParagraph:
řádek   34:
E684: list index out of range: 84
Chyba při zpracování function ctrlsf#Save..ctrlsf#edit#Save..<SNR>156_SaveFile..<SNR>156_VerifyConsistent:
řádek    6:
E684: list index out of range: 61
E15: Chybný výraz: line.content !=# a:on_disk[ln-1]
Chyba při zpracování function ctrlsf#Save..ctrlsf#edit#Save..<SNR>156_SaveFile..<SNR>156_WriteParagraph:
řádek   34:
E684: list index out of range: 61
23 files are saved.

**Comment by tex** [comment]
Most files are saved correctly as the last line states.

**Comment by dyng** [comment]
It's an issue related to `ag`, which I have reported to `ag` project:

https://github.com/ggreer/the_silver_searcher/issues/685

But if it's hard to be fixed in `ag` upstream, the only way is to workaround it in CtrlSF. I'll create a new issue about it. Thank you for your report.

**Comment by tex** [comment]
Thank hou for great plugin! It is awesome!
