### ISSUE TITLE
Asynchronous search with Neovim or vim-dispatch

### ISSUE THREAD

**Issue by dangerzone** [dyng/ctrlsf.vim#61]
[vim-grepper](https://github.com/mhinz/vim-grepper) has asynchronous search with Neovim or vim-dispatch. It'd be great if ctrlsf has it too, which might be useful for searching on a large code base.

**Comment by dyng** [comment]
There are several times I have thought about implementing an asyncrous search, but eventually I decide not to do it at all. The reason for that is I think search is not like a compilation or full unit tests which you don't need the result immediately, on the contrary, usually you are waiting for the search result to do something you want, which is obviously a *synchrous* flow.

Another reason is for a *REALLY SLOW* query (probably over 10,000+ hits), parsing result will consume a bunch of time which is significantly more than search itself, running search in background can only save a less significant part.

A third reason is `vim-dispatch` puts feedback in quickfix window, but currently CtrlSF is not using it.

**Comment by dyng** [comment]
Close this issue.

Thank you for your suggestion anyway, performance on large code base needs more work to do. A pull-request is really appreciated.
