### ISSUE TITLE
-filetype doesn't work

### ISSUE THREAD

**Issue by tex** [dyng/ctrlsf.vim#62]
Tokens: ['-filetype', 'wrproject', 'TarExtr']
ParsedResult: {'pattern': 'TarExtr', 'filetype': 'wrproject'}
Options: {'pattern': 'TarExtr', 'filetype': 'wrproject', '_vimregex': '\V\CTarExtr', '_vimhlregex': '\V\C\(\^\d\+:\.\*\)\@<=TarExtr'}
Tokens: ['-C', '3']
ParsedResult: {'context': 3}
ProjectRoot: .
ExecCommand: ag --context=3  --smart-case --literal --wrproject --noheading --nogroup --nocolor --nobreak 'TarExtr' /home/msvoboda/work/cots/LNX
Failed to call backend. Error messages: ag: unrecognized option '--wrproject'^@^@Usage: ag [FILE-TYPE] [OPTIONS] PATTERN [PATH]^@^@  Recursively search for PATTERN in PATH.^@  Like grep or ack, but f
aster.^@^@Example:^@  ag -i foo /bar/^@^@Output Options:^@     --ackmate            Print results in AckMate-parseable format^@  -A --after [LINES]      Print lines after match (Default: 2)^@  -B --b
efore [LINES]     Print lines before match (Default: 2)^@     --[no]break          Print newlines between matches in different files^@                          (Enabled by default)^@  -c --count     
         Only print the number of matches in each file.^@                          (This often differs from the number of matching lines)^@     --[no]color          Print color codes in results (Enab
led by default)^@     --color-line-number  Color codes for line numbers (Default: 1;33)^@     --color-match        Color codes for result match numbers (Default: 30;43)^@     --color-path         Col
or codes for path names (Default: 1;32)^@     --column             Print column numbers in results^@     --[no]filename       Print file names (Enabled unless searching a single file)^@  -H --[no]hea
ding        Print file names before each file's matches^@                          (Enabled by default)^@  -C --context [LINES]    Print lines before and after matches (Default: 2)^@     --[no]group 
         Same as --[no]break --[no]heading^@  -g PATTERN              Print filenames matching PATTERN^@  -l --files-with-matches Only print filenames that contain matches^@                          
(don't print the matching lines)^@  -L --files-without-matches^@                          Only print filenames that don't contain matches^@     --[no]numbers        Print line numbers. Default is to 
omit line numbers^@                          when searching streams^@  -o --only-matching      Prints only the matching part of the lines^@     --print-long-lines   Print matches on very long lines (
Default: >2k characters)^@     --passthrough        When searching a stream, print all lines even if they^@                          don't match^@     --silent             Suppress all log messages, 
including errors^@     --stats              Print stats (files scanned, time taken, etc.)^@     --vimgrep            Print results like vim's :vimgrep /pattern/g would^@                          (it 
reports every match on the line)^@  -0 --null --print0      Separate filenames with null (for 'xargs -0')^@^@Search Options:^@  -a --all-types          Search all files (doesn't include hidden files^
@                          or patterns from ignore files)^@  -D --debug              Ridiculous debugging (probably not useful)^@     --depth NUM          Search up to NUM directories deep (Default: 
25)^@  -f --follow             Follow symlinks^@  -F --fixed-strings      Alias for --literal for compatibility with grep^@  -G --file-search-regex  PATTERN Limit search to filenames matching PATTERN
^@     --hidden             Search hidden files (obeys .*ignore files)^@  -i --ignore-case        Match case insensitively^@     --ignore PATTERN     Ignore files/directories matching PATTERN^@      
                    (literal file/directory names also allowed)^@     --ignore-dir NAME    Alias for --ignore for compatibility with ack.^@  -m --max-count NUM      Skip the rest of a file after NUM 
matches (Default: 10,000)^@     --one-device         Don't follow links to other devices.^@  -p --path-to-agignore STRING^@                          Use .agignore file at STRING^@  -Q --literal      
      Don't parse PATTERN as a regular expression^@  -s --case-sensitive     Match case sensitively^@  -S --smart-case         Match case insensitively unless PATTERN contains^@                      
    uppercase characters (Enabled by default)^@     --search-binary      Search binary files for matches^@  -t --all-text           Search all text files (doesn't include hidden files)^@  -u --unrest
ricted       Search all files (ignore .agignore, .gitignore, etc.;^@                          searches binary and hidden files as well)^@  -U --skip-vcs-ignores   Ignore VCS ignore files^@           
               (.gitignore, .hgignore, .svnignore; still obey .agignore)^@  -v --invert-match^@  -w --word-regexp        Only match whole words^@  -z --search-zip         Search contents of compresse
d (e.g., gzip) files^@^@File Types:^@The search can be restricted to certain types of files. Example:^@  ag --html needle^@  - Searches for 'needle' in files with suffix .htm, .html, .shtml or .xhtml
.^@^@For a list of supported file types run:^@  ag --list-file-types^@^@

**Comment by dyng** [comment]
As the error message implies, filetype `wrproject` (I'm not sure what is this type) is not supported by `ag`.

What CtrlSF do is passing your filetype parameter to backend only, the actual work is up to your backend, there is no magic here.

**Comment by dyng** [comment]
But I admit that error message is printed some what confusing, I have fixed this problem and will be released in `v1.21`.

**Comment by tex** [comment]
Well, basically, what I expect from the filetype feature is that is searches only files with specified extension. A way how to specify -G parameter to `ag`. The `wrproject` is extension I want CtrlSF to grep.

**Comment by dyng** [comment]
At the first time I want to use `-G` option of Ag to get things done but I found this option is marked deprecated and removed in Ack2, so there is no straightforward solution here. I have considered:

1. Use `-G` for Ag and pipe along with `-x` for Ack2.
2. Apply filtering in CtrlSF.

**Comment by tex** [comment]
I think, the 1 is better. Detect whether Ack or Ack2 are on system.

**Comment by dyng** [comment]
I have implemented this feature in the latest `v1.4` branch, and there is a bit of time before it will be merged into `master`. If you will, please test it and feel free to report any issue, thx!

**Comment by wuxinxinggg** [comment]
let g:ackprg = 'ag --nogroup --nocolor --column --cc --cpp --java'
ag --context=3  --smart-case --literal  --noheading --nogroup --nocolor --nobreak 'Hello World'

确实没有起作用

**Comment by tex** [comment]
I tested it and it works nice. I like it.

**Comment by dyng** [comment]
V1.4 has been merged into master. (sorry for this so late merge)

Thank you for your feature suggestion!
