### ISSUE TITLE
Please support adding all matches to the quickfixlist

### ISSUE THREAD

**Issue by chrisbra** [dyng/ctrlsf.vim#63]
As per the title. I really love the :CtrlSF functionality, but sometimes it would be handy, having all matches in the quickfixlist. This has the advantage of having a quick overview of how many matches there are and second, one could make use of a quickfixdo command (which hopefully will be a Vim builtin soon)

**Comment by dyng** [comment]
It is not difficult to implement as CtrlSF maintains a parsed result of matches within itself, which you can verify in `echo ctrlsf#db#ResultSet()`. Feed `setqflist()` with the data will do the job.

But there is also needs of adding option, updating document, and so on... er, I will consider to add this feature in next release.

**Comment by chrisbra** [comment]
Thanks. I'll check it out and will provide a PR then.

**Comment by dyng** [comment]
Glad to hear that :)

I have updated `v1.3` branch just now, and I think `ctrlsf#db#MatchList` may help you. Please have a look at it.

**Comment by chrisbra** [comment]
Opened PR [#66](https://github.com/dyng/ctrlsf.vim/pull/66)

**Comment by dyng** [comment]
Merged in #67
