### ISSUE TITLE
g:ctrlsf_position at doc/ctrlsf.txt example mismatch with autoload/ctrlsf/preview.vim

### ISSUE THREAD

**Issue by ollyblue** [dyng/ctrlsf.vim#68]
in doc/ctrlsf.txt about g:ctrlsf_position is:
let g:ctrlsf_position = 'below'

but in autoload/ctrlsf/preview.vim:
    let openpos = {
            \ 'bottom': 'leftabove',  'right' : 'leftabove vertical',
            \ 'top'   : 'rightbelow',  'left' : 'rightbelow vertical'}
            \[g:ctrlsf_position] . ' '

**Comment by dyng** [comment]
I'm sorry for this misleading document (may have wasted a lot of your time debugging), I'll fix it soon.
