### ISSUE TITLE
Conflict 

### ISSUE THREAD

**Issue by ThomasZJ** [dyng/ctrlsf.vim#70]
When I installed the airline and ctrlsf , vim become very slow start , and retrieved when using ctrlsf vim crash
I using MacOS(10.10.5)  macvim(7.4.769)

唉，还是中文吧，感觉这句有点问题。。。
装了ctrlsf和airline之后，vim启动会变得很缓慢，而且使用ctrlsf检索的时候vim会呈现出假死状态
使用系统是MacOS（10.10.5）macvim(7.4.769)

**Comment by dyng** [comment]
信息太少，我也没法定位错误所在，只能提一些可能的建议帮助你debug。

1. 把其他所有插件禁用掉，确认依然存在问题。然后把airline和ctrlsf其中任意一个禁掉，确认问题解决。
2. 创建一个log文件，并用`tail`监视它。

    ```vim
    touch /tmp/vim-start.log
    tail -f /tmp/vim-start.log
    ```

3. 开另一个终端，用verbose mode启动vim，把日志打印到刚才的文件里。

    ```vim
    vim -V10/tmp/vim-start.log
    ```

4. 看日志文件什么时候出现长时间的停顿，查找上下文。

**Comment by dyng** [comment]
因为缺乏进一步的信息，暂时关闭本issue。

如果关于本issue有任何新的进展，请重开本issue，谢谢！
