### ISSUE TITLE
Ack2? or Ack1

### ISSUE THREAD

**Issue by jwmann** [dyng/ctrlsf.vim#75]
Hi there,

I noticed that the repo you've linked in the README.md is to Ack1.0. Currently that repo is no longer maintained and it directs you to use Ack2.

Does Ack2 work with this plugin?  
Or should I just use Ag instead?

Please let me know, thanks :)

**Comment by dyng** [comment]
Thank you for reminding me that the link is outdated.

CtrlSF should work with Ack2 well (if not, it may be a bug), and I have only plan to support Ack2 (maybe it can be used with Ack1 but I can't guarantee it). But after all, I suggest to use Ag because it's faster.

**Comment by dyng** [comment]
And I have updated the README, thanks!
