### ISSUE TITLE
<Plug>CtrlSFPrompt ignores let g:ctrlsf_regex_pattern = 1

### ISSUE THREAD

**Issue by jwmann** [dyng/ctrlsf.vim#76]
While setting the default search pattern to use regex with `let g:ctrlsf_regex_pattern = 1`
It is expected that `<Plug>CtrlSFPrompt` will result in:

`:CtrlSF -R <awaiting input>`

except it continues to return its regular `:CtrlSF <awaiting input>`

I realize that I can easily workaround this by mapping it like `nnoremap <leader>F :CtrlSF -R `
However I feel like the internal plugin mappings should be following its own conventions.

Please let me know.
Thanks

**Comment by dyng** [comment]
There is a misunderstanding in `g:ctrlsf_regex_pattern` that it doesn't append `-R` for you but **make the search itself be using regular expression**.

If you have set `g:ctrlsf_regex_pattern`, you have no need to add `-R`, it is implicitly applied.

**Comment by jwmann** [comment]
Oh okay, my mistake. I didn't properly check to see if that was the case.
Thank you!

**Comment by dyng** [comment]
Never mind, your are welcome :)
