### ISSUE TITLE
When the current dir is no .git or other project...

### ISSUE THREAD

**Issue by sundiontheway** [dyng/ctrlsf.vim#77]
I have set this:
let g:ctrlsf_default_root = 'project'

But when the current dir is not project, ctrlsf.vim will throw an error.
I think it could be switched default root more automaticly :)

**Comment by dyng** [comment]
Could you post the error message about what happened when the project root was not found?

CtrlSF should search **current file** if no project root is found, if that is not the case, maybe it's a bug.

**Comment by sundiontheway** [comment]
![error_msg_01](https://cloud.githubusercontent.com/assets/5465534/10567795/1f3e9024-7640-11e5-9737-22e8b464a8af.png)
![error_msg_02](https://cloud.githubusercontent.com/assets/5465534/10567797/212ff21a-7640-11e5-95bf-c0464c8f6dd7.png)

When search "sudo" at the home dir in vimrc file.

**Comment by sundiontheway** [comment]
My OS is Linux mint 17.02, gvim 7.4

**Comment by dyng** [comment]
Well, it's a problem about output from Ack if only a file is specified, I need some time to fix it.

Before that, you can switch to Ag by `let g:ctrlsf_ack = 'ag'`, to work around it.

**Comment by dyng** [comment]
Fixed in V1.4 and merged, thank you for your bug report!
