### ISSUE TITLE
忽略某个文件夹，如node_modules

### ISSUE THREAD

**Issue by franckXu** [dyng/ctrlsf.vim#80]
如何忽略某个文件夹，如node_modules,
Ack 文档里 有 –[no]ignore-dir=name 这个option，
ctrlSF有忽略某个文件夹的功能吗？

**Comment by dyng** [comment]
目前还没有针对`--ignore-dir`的支持，不过有考虑过在下一个版本中添加。谢谢你的建议！

**Comment by xream** [comment]
其实可以考虑让用户自己配置搜索的默认命令
这样就能自由设置使用 ag 还是 pt, 然后 ignore 也可以自己配置

**Comment by dyng** [comment]
@xream 

在v1.0版本以前ctrlsf支持任意的搜索命令，但是考虑到要保证ack和ag下的行为一致有点困难，所以v1.0以后就取消了。这是Readme中对此的说明：

https://github.com/dyng/ctrlsf.vim/tree/c5e68e82eacb67134428ec94cbbea5443164b5c2#where-and-why-backward-compatibility-is-given-up

不过自定义参数确实可以考虑，谢谢你的建议。

p.s. 目前ctrlsf还不支持pt，虽然可以通过修改`g:ctrlsf_ackprg`参数来调用pt，但是ctrlsf内部处理中对non-ag的后端都作为ack处理，所以可能存在不兼容的问题。

**Comment by dyng** [comment]
已经增加了`-ignoreidr`和`g:ctrlsf_ignore_dir`选项，并merge到master分支。

Example:

```vim
" 搜索时忽略 node_modules
:CtrlSF -ignoredir 'node_modules' 'console.log'

" 默认忽略 node_modules
let g:ctrlsf_ignore_dir = ["node_modules"]
```
