### ISSUE TITLE
Only one file name allowed

### ISSUE THREAD

**Issue by brucedsu** [dyng/ctrlsf.vim#81]
<img width="736" alt="screen shot 2015-11-27 at 10 32 36 am" src="https://cloud.githubusercontent.com/assets/4081120/11446855/4021c52e-94f2-11e5-8a3c-0627e6b4f1b6.png">
在 printf 那一行按回车，会提示 "Only one file name allowed"
<img width="796" alt="screen shot 2015-11-27 at 10 31 14 am" src="https://cloud.githubusercontent.com/assets/4081120/11446863/554b488a-94f2-11e5-98c3-22b94319620d.png">
我觉得原因是文件路径中的空格没有 escape 掉。
最后谢谢做了这么好的插件。

**Comment by dyng** [comment]
谢谢你的bug报告，确实是所有的空格没有被escape掉的关系。

我会尽快地修复这个问题。

**Comment by dyng** [comment]
已merge，请更新到最新版。

如果还有bug，可继续在本issue里提出，谢谢。

**Comment by jason-xhy** [comment]
:+1:   刚刚才发现作者是国人，牛。
