### ISSUE TITLE
Search a function

### ISSUE THREAD

**Issue by jason-xhy** [dyng/ctrlsf.vim#83]
I tried to search function x() in my project. It's been called in 3 files(i.c j.c k.c), and they are in the same path.

My problem is:
 The result shows that x() has been called in i.c and j.c but not in k.c. But it's really also been called in k.c. I don't know what happened.

**Comment by dyng** [comment]
可能是后端返回的结果本身有问题，请在debug模式下查看实际运行的命令，然后自己的终端下跑一遍看看结果是否有问题。

1. 打开debug模式。

    ```
    let g:ctrlsf_debug_mode = 1
    ```

2. 寻找所执行命令的log。

    ```
    ExecCommand: ag --context=3 ...
    ```

3. 在终端下重新执行。

**Comment by jason-xhy** [comment]
部分信息我用中文代替，目标函数为x().
Tokens: ['目标函数']

ParsedResult: {'pattern': '目标函数'}

Options: {'pattern': '目标函数', '_vimregex': '\V\C目标函数', '_vimhlregex': '\V\C\(\^\d\+:\.\*\)\@<=目标函数'}

ProjectRoot: /根目录/1/2

ExecCommand: ag --context=3  --smart-case --literal --noheading --nogroup --nocolor --nobreak '目标函数' '/根目录/1/2'
......省略......
DefactorizeLine: [Factor]: [/根目录/1/2/3/4/5/6/i.c, 100,	xxx = x(a,b);], [Orig]: /根目录/1/2/3/4/5/6/i.c:100-xxx = x(a,b);
......省略......



问题现象： 
	k.c跟i.c都位于/根目录/1/2/3/4/5/6/目录下，但是搜索log显示只进入了i.c文件进行搜索，并没有进入k.c文件。

**Comment by dyng** [comment]
首先，因为ctrlsf不具备搜索的功能，只是解析了ag的搜索结果，**所以请先确认ag的搜索结果中包含了k.c**，在终端下运行以下命令

```
ag --context=3 --smart-case --literal --noheading --nogroup --nocolor --nobreak '目标函数' '/根目录/1/2'
```

看`k.c`是否出现在结果列表中。

因为你的日志不太完整，我只能猜测一些可能的原因：

1.（k.c**没有**出现在ag的结果列表中）可能是k.c被ag忽略了，检查一下k.c是否在`.gitignore`，`.agignore`等忽略列表里。
2.（k.c出现在ag的结果列表中）可能是ctrlsf的bug，请把完整的日志截图发在这个issue下。如果包含敏感信息的话，请建一个测试项目重现一下这个bug。**另外请附上os，vim，shell，ag的版本信息**。

**Comment by jason-xhy** [comment]
我运行了你说的命令，列表中没有出现k.c。
于是我在命令选项中加上了-u ，有趣的事情发生了：Binary file /…/…/k.c matches

不知道这个文件为什么被识别成了二进制文件，而且是在文件名为“.c”的情况下

**Comment by dyng** [comment]
https://github.com/ggreer/the_silver_searcher/blob/a99b010f411e56b5ab6c7033cc966275db311973/src/util.c#L287-L339

这是ag判断binary文件的方法，你可以参考一下。（我感觉可能是文件里插入了字面量的"\0"）
如果确认不是ctrlsf的问题，请随后关闭本issue。

**Comment by jason-xhy** [comment]
这两天很忙没能及时跟进，抱歉。
感谢dyng提供的思路，原因已经找到了，与ctlsf 无关。
我把ag判断binary的函数进行了修改，通过打印发现k.c的注释中出现了太多ag认为的可疑字符，导致k.c被识别为binary文件。将k.c注释中的这些可疑字符去掉即可。
修改后的函数:
/* This function is very hot. It's called on every file. */
int is_binary(const void *buf, const size_t buf_len) {
    size_t suspicious_bytes = 0;
    size_t total_bytes = buf_len > 512 ? 512 : buf_len;
    const unsigned char *buf_c = buf;
    size_t i;

    if (buf_len == 0) {
        fprintf(out_fd, "    %s    line%d\r",__func__,__LINE__);
        return 0;
    }

    if (buf_len >= 3 && buf_c[0] == 0xEF && buf_c[1] == 0xBB && buf_c[2] == 0xBF) {
        fprintf(out_fd, "    %s    line%d\r",__func__,__LINE__);
        /* UTF-8 BOM. This isn't binary. */
        return 0;
    }

    if (buf_len >= 4 && strncmp(buf, "%PDF-", 5) == 0) {

        fprintf(out_fd, "    %s    line%d\r",__func__,__LINE__);

        /* PDF. This is binary. */
        return 1;
    }

    for (i = 0; i < total_bytes; i++) {
        if (buf_c[i] == '\0') {
            fprintf(out_fd, "    %s    line%d\r",__func__,__LINE__);
            /* NULL char. It's binary */
            return 1;
        } else if ((buf_c[i] < 7 || buf_c[i] > 14) && (buf_c[i] < 32 || buf_c[i] > 127)) {
            /* UTF-8 detection */
            if (buf_c[i] > 193 && buf_c[i] < 224 && i + 1 < total_bytes) {
                i++;
                if (buf_c[i] > 127 && buf_c[i] < 192) {
                    continue;
                }
            } else if (buf_c[i] > 223 && buf_c[i] < 240 && i + 2 < total_bytes) {
                i++;
                if (buf_c[i] > 127 && buf_c[i] < 192 && buf_c[i + 1] > 127 && buf_c[i + 1] < 192) {
                    i++;
                    continue;
                }
            }
            suspicious_bytes++;
            fprintf(out_fd, " buf_c[%d] is %c  suspicious_bytes is %d\r\n  %s    line%d\r",i,buf_c[i],suspicious_bytes,__func__,__LINE__);
            /* Disk IO is so slow that it's worthwhile to do this calculation after every suspicious byte. */
            /* This is true even on a 1.6Ghz Atom with an Intel 320 SSD. */
            /* Read at least 32 bytes before making a decision */
            if (i >= 32 && (suspicious_bytes * 100) / total_bytes > 10) {
                fprintf(out_fd, "    %s    line%d\r",__func__,__LINE__);

                return 1;
            }
        }
    }
    if ((suspicious_bytes * 100) / total_bytes > 10) {

        fprintf(out_fd, "    %s    line%d\r",__func__,__LINE__);
        return 1;
    }

    return 0;
}


运行命令：ag -u --context=3 --smart-case --literal --noheading --nogroup --nocolor --nobreak '0' '.'
打印信息：
  buf_c[173] is 3  suspicious_bytes is 1

  is_binary    line332
 buf_c[175] is -  suspicious_bytes is 2

  is_binary    line332
 buf_c[177] is ? suspicious_bytes is 3

  is_binary    line332
 buf_c[183] is 3  suspicious_bytes is 4

  is_binary    line332
 buf_c[185] is ¤  suspicious_bytes is 5

  is_binary    line332
 buf_c[187] is ￥  suspicious_bytes is 6

  is_binary    line332
 buf_c[188] is ??uspicious_bytes is 7

  is_binary    line332
 buf_c[189] is ¨  suspicious_bytes is 8

  is_binary    line332
 buf_c[191] is *  suspicious_bytes is 9

  is_binary    line332
 buf_c[217] is ±  suspicious_bytes is 10

  is_binary    line332
 buf_c[218] is μ  suspicious_bytes is 11

  is_binary    line332
 buf_c[219] is |  suspicious_bytes is 12

  is_binary    line332
 buf_c[220] is ?  suspicious_bytes is 13

  is_binary    line332
 buf_c[234] is a  suspicious_bytes is 14

  is_binary    line332
 buf_c[235] is o  suspicious_bytes is 15

  is_binary    line332
 buf_c[236] is ¤  suspicious_bytes is 16

  is_binary    line332
 buf_c[237] is ?  suspicious_bytes is 17

  is_binary    line332
 buf_c[238] is -  suspicious_bytes is 18

  is_binary    line332
 buf_c[239] is ±  suspicious_bytes is 19

  is_binary    line332
 buf_c[264] is ￥  suspicious_bytes is 20
	......
Binary file k.c matches.
再次感谢dyng！

**Comment by dyng** [comment]
不客气 :)

你如果觉得ag判断binary的方法需要改进的话，也可以给ag提起pull request
