### ISSUE TITLE
Could ctrlsf search only in the current buffer

### ISSUE THREAD

**Issue by nathan-huang** [dyng/ctrlsf.vim#84]
Is there any way to search in the current buffer or the opened buffer？

**Comment by dyng** [comment]
To search in current buffer, you can make it by following command: `:CtrlSF 'foo' %`.

By 'opened buffer' I assume that you mean 'all opened buffers', there is no builtin way to do this, you need to list all of their names in the command.

**Comment by nathan-huang** [comment]
Thanks
