### ISSUE TITLE
Errors generated when using "CtrlSF -R"

### ISSUE THREAD

**Issue by steven807** [dyng/ctrlsf.vim#86]
I'm not sure why others aren't seeing this, but I found that I couldn't do regex searches.  After some time debugging, I found that the command being passed was "ag ... --ignore-dir --noheading...".  In other words, the "--ignore-dir" didn't have a directory after it, so it was consuming the "--noheading", preventing the output of "ag" from being parsable.

I later found that ctrlsf#opt#GetIgnoreDir() was returning [''] instead of an empty list.  I changed the code in the following way:

    func! ctrlsf#opt#GetIgnoreDir() abort
        let dopt = ctrlsf#opt#GetOpt("ignoredir")
        let gopt = g:ctrlsf_ignore_dir
        if (gopt != [] && dopt != '')
            return add(copy(gopt), dopt)
        elseif dopt != ''
            return [dopt]
        elseif gopt != []
            return gopt
        else
            return []
        endif
    endf

**Comment by dyng** [comment]
`--ignore-dir` is an argument added in latest version, sorry for lack of test and it seems to be buggy. Thank you for your bug report and I'm really sorry for this inconvenience.

I'll fix this issue as soon as possible.

**Comment by dyng** [comment]
@steven807 I think this issue should be fixed in the latest version, thank you for your bug report!

**Comment by steven807** [comment]
Works great, thanks!
