### ISSUE TITLE
怎么设置给一个项目设置多个文件夹？

### ISSUE THREAD

**Issue by alexsunxl** [dyng/ctrlsf.vim#88]
比如我在 /app/a/ 文件夹下面开发， 想只搜索 /app/a/ 和 /app/b/ 的内容。
这个设置最好只对 /app/a/这个项目起作用。 如果不行的话是全局配置也可以的
不能配置的话，每次都要手打太麻烦了

看了一下文档，有一个g:ctrlsf_default_root 参数，
但是不太懂怎么设置。
感谢 ^ - ^

**Comment by dyng** [comment]
`g:ctrlsf_default_root` 有两种可选的值:  `cwd` ,  `project` 。

`cwd`: 根据你的当前目录，比如你目前在`/app/a/`下，则搜索范围是`/app/a/`。
`project`: 会向上搜索 vcs 目录（例如 `.git`, `svn` 等），找到 vcs 目录后，搜索范围为该目录所在的目录。所以如果你在 `/app/a/` 下但想同时搜索 `/app/b/` 的文件的话，需要在 `/app` 目录下放置 `.git` 目录。

目前没有其他的可用办法。

**Comment by alexsunxl** [comment]
@dyng  感谢解答

**Comment by dyng** [comment]
不客气 :)

如果问题已经解决的话请关闭issue。
