### ISSUE TITLE
Support for the platinum searcher?

### ISSUE THREAD

**Issue by demon386** [dyng/ctrlsf.vim#89]
see https://github.com/monochromegane/the_platinum_searcher

**Comment by dyng** [comment]
`pt`'s interface looks a bit different from `ag`'s but it seems to be enough for CtrlSF's usage, however the real challenge is to provide a same user experience for these 3 search program: `ack`, `ag` and `pt`.

I'll consider about it, thank you for your suggestion!

**Comment by dyng** [comment]
@demon386 I have added pt as a backend in branch `1.6`, but it is not fully test yet, could you do me a favor to test it? Thanks!

I have also added a new option `g:ctrlsf_extra_backend_args` that can be used to pass arguments such as `--home-ptignore` or `--global-gitignore` to `pt`.

**Comment by demon386** [comment]
OK. I'll start to test it.

**Comment by demon386** [comment]
I have used it for a while and it seems to work fine.

**Comment by dyng** [comment]
OK, thanks for your testing, I'll try to merge it into `master`.

**Comment by dyng** [comment]
`1.6` has been merged into `master`, close this issue.

Need to mention that `g:ctrlsf_extra_backend_args`'s format is also changed, now it accepts a dictionary that can specify different extra arguments for different backend.

```vim
let g:ctrlsf_extra_backend_args = {
    \ 'pt': '--home-ptignore'
    \ }
```
