### ISSUE TITLE
ctrlsf should use unlisted buffer.

### ISSUE THREAD

**Issue by wsdjeg** [dyng/ctrlsf.vim#97]
I am using vim-airline,and it will list all buffers in the tab line,now it will show `__ctrlsf__` buffer, but I think this plugin should use ulisted buffer same as vimfiler tagbar and so on.

**Comment by dyng** [comment]
Sorry for this late reply.

I can't reproduce this issue, actually CtrlSF should use an unlisted buffer to serve a main window, (you can check code [here](https://github.com/dyng/ctrlsf.vim/blob/master/autoload/ctrlsf/win.vim#L113)).

If you are sure in some case CtrlSF's window can *become* 'listed buffer', it can be a bug. Please update this issue with how to reproduce, thank you!

**Comment by wsdjeg** [comment]
I test with this minivimrc in the git repo
localtest/test.vim
```vim
exec "set rtp+=" . fnamemodify(expand('<sfile>'), ':h:h')
```
that means add current dir into runtimepath of vim

reproduced step
1. vim -u localtest/test.vim
2.`:CtrlSF a<CR>`
3. `:set buflisted?` show me nobuflisted
4.`q` to close ctrlsf buffer
5.`:CtrlSF a<CR>` again
6. `:set buflisted?` show me buflisted

**Comment by wsdjeg** [comment]
ok I got it ,and I will fix it,
```diff
diff --git a/autoload/ctrlsf/win.vim b/autoload/ctrlsf/win.vim
index 4677775..6a1ff25 100644
--- a/autoload/ctrlsf/win.vim
+++ b/autoload/ctrlsf/win.vim
@@ -100,7 +100,7 @@ func! s:InitMainWindow() abort
     if exists("b:ctrlsf_initialized")
         return
     endif
-
+    echom 1
     " option
     setl filetype=ctrlsf
     setl fileformat=unix
```
use this `echom 1`, I found the windows init func only be executed once, the second time I use `CtrlSF a`,`exists("b:ctrlsf_initialized")` return 1, so it is finished

**Comment by wsdjeg** [comment]
Fixed
